import { PassThrough, Writable } from "node:stream";
import { EventEmitter } from "node:events";

type NetlifyEvent = {
  httpMethod: string;
  path: string;
  rawUrl?: string;
  headers?: Record<string, string>;
  multiValueHeaders?: Record<string, string[]>;
  queryStringParameters?: Record<string, string>;
  rawQuery?: string;
  body?: string | null;
  isBase64Encoded?: boolean;
};

type NetlifyContext = unknown;
type ExpressApp = (req: any, res: any) => void;

let cachedApp: ExpressApp | null = null;

async function getApp(): Promise<ExpressApp> {
  if (!cachedApp) {
    // server-app.mjs is generated by scripts/build-netlify-replacement.mjs into the final function folder.
    // @ts-ignore generated Netlify bundle artifact
    const mod = await import("../../dist/server.cjs");
    cachedApp = mod.default;
  }
  return cachedApp;
}

function getApiPath(event: NetlifyEvent): string {
  const original = event.headers?.["x-nf-original-url"] || event.headers?.["X-Nf-Original-Url"] || event.rawUrl || event.path;
  let pathname = event.path || "/";
  let search = "";
  try {
    const url = original.startsWith("http") ? new URL(original) : new URL(original, "https://netlify.local");
    pathname = url.pathname;
    search = url.search;
  } catch {
    search = event.rawQuery ? `?${event.rawQuery}` : "";
  }

  pathname = pathname
    .replace(/^\/\.netlify\/functions\/api\/?/, "/api/")
    .replace(/^\/api\/?/, "/api/");

  if (pathname === "/api") pathname = "/api/";
  return `${pathname}${search}`;
}

function createRequest(event: NetlifyEvent): any {
  const body = event.body
    ? Buffer.from(event.body, event.isBase64Encoded ? "base64" : "utf8")
    : Buffer.alloc(0);
  const req = new PassThrough() as any;
  req.url = getApiPath(event);
  req.originalUrl = req.url;
  req.method = event.httpMethod;
  req.headers = Object.fromEntries(Object.entries(event.headers || {}).map(([key, value]) => [key.toLowerCase(), value]));
  req.connection = { encrypted: true, remoteAddress: req.headers["x-nf-client-connection-ip"] || req.headers["client-ip"] || "" };
  req.socket = req.connection;
  req.ip = req.connection.remoteAddress;
  req.protocol = "https";
  req.secure = true;
  req.push(body);
  req.push(null);
  return req;
}

function createResponse(): { res: any; done: Promise<any> } {
  const chunks: Buffer[] = [];
  const emitter = new EventEmitter();
  const headers = new Map<string, string | string[]>();
  const res = new Writable({
    write(chunk, _encoding, callback) {
      chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk));
      callback();
    },
  }) as any;

  res.statusCode = 200;
  res.statusMessage = "OK";
  res.headersSent = false;
  res.setHeader = (name: string, value: string | string[]) => {
    headers.set(name.toLowerCase(), value);
    return res;
  };
  res.getHeader = (name: string) => headers.get(name.toLowerCase());
  res.getHeaders = () => Object.fromEntries(headers);
  res.removeHeader = (name: string) => headers.delete(name.toLowerCase());
  res.writeHead = (statusCode: number, statusMessageOrHeaders?: string | Record<string, string>, maybeHeaders?: Record<string, string>) => {
    res.statusCode = statusCode;
    const nextHeaders = typeof statusMessageOrHeaders === "string" ? maybeHeaders : statusMessageOrHeaders;
    Object.entries(nextHeaders || {}).forEach(([name, value]) => res.setHeader(name, value));
    res.headersSent = true;
    return res;
  };
  const originalEnd = res.end.bind(res);
  res.end = (chunk?: any, encoding?: BufferEncoding, callback?: () => void) => {
    if (chunk) chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk, encoding));
    originalEnd(callback);
    emitter.emit("finish");
    return res;
  };

  return {
    res,
    done: new Promise(resolve => {
      emitter.once("finish", () => {
        const responseHeaders = Object.fromEntries(headers);
        resolve({
          statusCode: res.statusCode,
          headers: responseHeaders,
          body: Buffer.concat(chunks).toString("utf8"),
        });
      });
    }),
  };
}

export async function handler(event: NetlifyEvent, _context: NetlifyContext) {
  const app = await getApp();
  const req = createRequest(event);
  const { res, done } = createResponse();
  app(req, res);
  return done;
}
