-- SPRINT 4A: Database Seed Script
-- Generated dynamically on 2026-06-27T10:31:42.231Z

TRUNCATE TABLE audit_logs CASCADE;
TRUNCATE TABLE report_snapshots CASCADE;
TRUNCATE TABLE ai_chat_messages CASCADE;
TRUNCATE TABLE notifications CASCADE;
TRUNCATE TABLE news CASCADE;
TRUNCATE TABLE exam_answers CASCADE;
TRUNCATE TABLE exam_attempts CASCADE;
TRUNCATE TABLE exams CASCADE;
TRUNCATE TABLE quiz_attempts CASCADE;
TRUNCATE TABLE questions CASCADE;
TRUNCATE TABLE learning_progress CASCADE;
TRUNCATE TABLE learning_assignments CASCADE;
TRUNCATE TABLE learning_sections CASCADE;
TRUNCATE TABLE learning_topics CASCADE;
TRUNCATE TABLE permissions CASCADE;
TRUNCATE TABLE roles CASCADE;
TRUNCATE TABLE users CASCADE;
TRUNCATE TABLE units CASCADE;

-- -----------------------------------------------------
-- SEEDING ROLES & PERMISSIONS
-- -----------------------------------------------------
INSERT INTO roles (name, description) VALUES ('guest', 'Vai trò guest') ON CONFLICT DO NOTHING;
INSERT INTO roles (name, description) VALUES ('member', 'Vai trò member') ON CONFLICT DO NOTHING;
INSERT INTO roles (name, description) VALUES ('instructor', 'Vai trò instructor') ON CONFLICT DO NOTHING;
INSERT INTO roles (name, description) VALUES ('political_officer', 'Vai trò political_officer') ON CONFLICT DO NOTHING;
INSERT INTO roles (name, description) VALUES ('admin', 'Vai trò admin') ON CONFLICT DO NOTHING;

INSERT INTO permissions (role_name, action, description) VALUES ('member', 'view_own_learning', 'Học tập chuyên đề cá nhân');
INSERT INTO permissions (role_name, action, description) VALUES ('member', 'take_own_quiz', 'Luyện tập trắc nghiệm cá nhân');
INSERT INTO permissions (role_name, action, description) VALUES ('member', 'take_own_exam', 'Thi chính thức cá nhân');
INSERT INTO permissions (role_name, action, description) VALUES ('instructor', 'manage_learning_topics', 'Quản lý bài giảng');
INSERT INTO permissions (role_name, action, description) VALUES ('instructor', 'manage_questions', 'Quản lý ngân hàng câu hỏi');
INSERT INTO permissions (role_name, action, description) VALUES ('instructor', 'manage_exams', 'Quản lý đề thi chính thức');
INSERT INTO permissions (role_name, action, description) VALUES ('instructor', 'view_learner_progress', 'Theo dõi tiến độ người học');
INSERT INTO permissions (role_name, action, description) VALUES ('political_officer', 'view_unit_reports', 'Xem báo cáo thống kê đơn vị');
INSERT INTO permissions (role_name, action, description) VALUES ('political_officer', 'view_weak_topics', 'Theo dõi chuyên đề yếu kém');
INSERT INTO permissions (role_name, action, description) VALUES ('political_officer', 'monitor_education_quality', 'Giám sát chất lượng giáo dục');
INSERT INTO permissions (role_name, action, description) VALUES ('political_officer', 'approve_users', 'Phê duyệt tài khoản đơn vị');
INSERT INTO permissions (role_name, action, description) VALUES ('admin', 'full_access', 'Toàn quyền hệ thống');

-- -----------------------------------------------------
-- SEEDING UNITS
-- -----------------------------------------------------
INSERT INTO units (id, name, type, parent_unit_id, description) VALUES ('10000000-0000-4000-8000-000000000001', 'Ban CHQS xã Yên Thế', 'Ban Chỉ huy Quân sự', NULL, 'Cơ quan quân sự địa phương xã Yên Thế');
INSERT INTO units (id, name, type, parent_unit_id, description) VALUES ('10000000-0000-4000-8000-000000000002', 'Trung đội dân quân cơ động', 'Trung đội', '10000000-0000-4000-8000-000000000001', 'Lực lượng sẵn sàng chiến đấu, tuần tra giữ gìn trật tự trị an địa phương');
INSERT INTO units (id, name, type, parent_unit_id, description) VALUES ('10000000-0000-4000-8000-000000000003', 'Thôn Yên Cư', 'Tổ dân quân Thôn', '10000000-0000-4000-8000-000000000001', 'Lực lượng tại chỗ thôn Yên Cư');
INSERT INTO units (id, name, type, parent_unit_id, description) VALUES ('10000000-0000-4000-8000-000000000004', 'Thôn Tân Sỏi', 'Tổ dân quân Thôn', '10000000-0000-4000-8000-000000000001', 'Lực lượng tại chỗ thôn Tân Sỏi');
INSERT INTO units (id, name, type, parent_unit_id, description) VALUES ('10000000-0000-4000-8000-000000000005', 'Thôn Dầm Chúc', 'Tổ dân quân Thôn', '10000000-0000-4000-8000-000000000001', 'Lực lượng tại chỗ thôn Dầm Chúc');

-- -----------------------------------------------------
-- SEEDING APP-MANAGED USERS
-- -----------------------------------------------------
INSERT INTO users (id, full_name, email, phone, password_hash, unit_id, role, account_status, must_change_password, created_at, updated_at, last_login_at) VALUES ('00000000-0000-4000-8000-000000000001', 'Quản trị viên', 'admin@example.com', '0900000001', '$2b$12$YRjZiG/hbXHIzYmG4OMVaOyQGKby81Fk0KIY8DbNI29SyI/Ff4pkq', '10000000-0000-4000-8000-000000000001', 'admin', 'active', false, '2026-01-01T00:00:00Z', '2026-06-25T11:00:00Z', NULL);
INSERT INTO users (id, full_name, email, phone, password_hash, unit_id, role, account_status, must_change_password, created_at, updated_at, last_login_at) VALUES ('00000000-0000-4000-8000-000000000002', 'Trần Đức Cường', 'cuong@example.com', '0912345678', '$2b$12$Ru/SAL4Gnasy4CIQnoG8yuIiVStm.3iCYF3dvumapMWX2wxVr.0pO', '10000000-0000-4000-8000-000000000001', 'political_officer', 'active', false, '2026-01-10T08:00:00Z', '2026-06-25T10:00:00Z', NULL);
INSERT INTO users (id, full_name, email, phone, password_hash, unit_id, role, account_status, must_change_password, created_at, updated_at, last_login_at) VALUES ('00000000-0000-4000-8000-000000000003', 'Giáo viên demo', 'instructor@example.com', '0900000003', '$2b$12$Ru/SAL4Gnasy4CIQnoG8yuIiVStm.3iCYF3dvumapMWX2wxVr.0pO', '10000000-0000-4000-8000-000000000001', 'instructor', 'active', false, '2026-01-15T09:00:00Z', '2026-06-24T14:20:00Z', NULL);
INSERT INTO users (id, full_name, email, phone, password_hash, unit_id, role, account_status, must_change_password, created_at, updated_at, last_login_at) VALUES ('00000000-0000-4000-8000-000000000004', 'Học viên demo', 'member@example.com', '0900000004', '$2b$12$Ru/SAL4Gnasy4CIQnoG8yuIiVStm.3iCYF3dvumapMWX2wxVr.0pO', '10000000-0000-4000-8000-000000000002', 'member', 'active', false, '2026-02-01T08:00:00Z', '2026-06-26T10:00:00Z', NULL);

-- -----------------------------------------------------
-- SEEDING LEARNING TOPICS
-- -----------------------------------------------------
INSERT INTO learning_topics (id, title, category, description, objective, content, content_type, estimated_minutes, required, deadline, difficulty, tags, references_data, created_by, created_at, updated_at, video_url, pdf_url, assigned_unit_ids, assigned_user_ids) VALUES ('t1', 'Giáo dục chính trị: Kiên định mục tiêu lý tưởng cách mạng', 'Giáo dục chính trị', 'Nội dung bồi dưỡng lập trường tư tưởng vững vàng, kiên định mục tiêu độc lập dân tộc gắn liền với chủ nghĩa xã hội của Đảng Cộng sản Việt Nam.', 'Giúp chiến sĩ dân quân hiểu rõ bản chất cách mạng, giữ vững tư tưởng trước những thông tin xuyên tạc, trung thành với Tổ quốc và nhân dân.', '### 1. Ý NGHĨA QUAN TRỌNG CỦA LÝ TƯỞNG CÁCH MẠNG
Lý tưởng cách mạng là kim chỉ nam cho mọi hành động của lực lượng vũ trang nhân dân Việt Nam. Trong suốt chiều dài lịch sử cách mạng, nhờ kiên định lý tưởng độc lập dân tộc và chủ nghĩa xã hội, quân và dân ta đã vượt qua muôn vàn khó khăn gian khổ để giành lại độc lập tự do.

### 2. CÁC NỘI DUNG CỐT LÕI
* **Kiên định Chủ nghĩa Mác - Lênin và Tư tưởng Hồ Chí Minh:** Đây là nền tảng tư tưởng, kim chỉ nam hành động của Đảng.
* **Mục tiêu Độc lập dân tộc gắn liền với Chủ nghĩa xã hội:** Là sợi chỉ đỏ xuyên suốt.
* **Trung thành vô hạn với Tổ quốc và Nhân dân:** Sẵn sàng chiến đấu, hy sinh vì sự nghiệp bảo vệ vững chắc Tổ quốc Việt Nam xã hội chủ nghĩa.

### 3. TRÁCH NHIỆM CỦA LỰC LƯỢNG DÂN QUÂN TỰ VỆ
* Tích cực học tập nâng cao nhận thức chính trị, rèn luyện phẩm chất đạo đức lối sống.
* Gương mẫu thực hiện tốt đường lối, chủ trương của Đảng, chính sách, pháp luật của Nhà nước.
* Cảnh giác trước âm mưu "diễn biến hòa bình", bạo loạn lật đổ của các thế lực thù địch.', 'document', 20, true, '2026-07-05T23:59:59Z', 'Trung bình', '["Giáo dục chính trị","Lập trường tư tưởng","Dân quân tự vệ"]'::jsonb, '["Nghị quyết Đại hội XIII của Đảng","Tài liệu giáo dục chính trị cho dân quân tự vệ năm 2026 - Bộ Quốc phòng"]'::jsonb, '00000000-0000-4000-8000-000000000003', '2026-06-15T08:00:00Z', '2026-06-15T08:00:00Z', NULL, NULL, '[]'::jsonb, '[]'::jsonb);
INSERT INTO learning_topics (id, title, category, description, objective, content, content_type, estimated_minutes, required, deadline, difficulty, tags, references_data, created_by, created_at, updated_at, video_url, pdf_url, assigned_unit_ids, assigned_user_ids) VALUES ('t2', 'Phổ biến giáo dục pháp luật: Nghĩa vụ quân sự và trách nhiệm công dân', 'Phổ biến giáo dục pháp luật', 'Giới thiệu các nội dung cốt lõi của Luật Nghĩa vụ quân sự 2015, quyền lợi và nghĩa vụ của công dân khi tham gia bảo vệ Tổ quốc.', 'Nắm vững tiêu chuẩn tuyển quân, độ tuổi gọi nhập ngũ, các trường hợp được hoãn hoặc miễn gọi nhập ngũ, trách nhiệm của bản thân và gia đình.', '### 1. Ý NGHĨA CỦA LUẬT NGHĨA VỤ QUÂN SỰ
Bảo vệ Tổ quốc là nghĩa vụ thiêng liêng và quyền cao quý của công dân. Thực hiện Nghĩa vụ quân sự (NVQS) là trách nhiệm của mỗi công dân Việt Nam.

### 2. CÁC QUY ĐỊNH CHÍNH TRONG LUẬT NVQS 2015
* **Độ tuổi gọi nhập ngũ:** Công dân nam đủ 18 tuổi đến hết 25 tuổi. Nếu học Đại học/Cao đẳng thì đến hết 27 tuổi.
* **Thời hạn phục vụ tại ngũ:** 24 tháng.
* **Các trường hợp được tạm hoãn:** Chưa đủ sức khỏe; là lao động duy nhất nuôi thân nhân không có khả năng lao động; học sinh học phổ thông, sinh viên đại học/cao đẳng chính quy...
* **Các trường hợp miễn gọi:** Con của liệt sĩ, con thương binh hạng 1...

### 3. XỬ LÝ VI PHẠM
* Trốn tránh nghĩa vụ quân sự có thể bị phạt hành chính rất nặng hoặc truy cứu trách nhiệm hình sự theo Điều 332 Bộ luật Hình sự.', 'document', 25, true, '2026-07-01T23:59:59Z', 'Trung bình', '["Nghĩa vụ quân sự","Pháp luật","Trách nhiệm công dân"]'::jsonb, '["Luật Nghĩa vụ quân sự năm 2015","Nghị định 37/2022/NĐ-CP của Chính phủ"]'::jsonb, '00000000-0000-4000-8000-000000000003', '2026-06-12T09:00:00Z', '2026-06-12T09:00:00Z', NULL, NULL, '[]'::jsonb, '[]'::jsonb);
INSERT INTO learning_topics (id, title, category, description, objective, content, content_type, estimated_minutes, required, deadline, difficulty, tags, references_data, created_by, created_at, updated_at, video_url, pdf_url, assigned_unit_ids, assigned_user_ids) VALUES ('t3', 'Kỷ luật Quân đội và nền nếp chính quy', 'Kỷ luật Quân đội', 'Quán triệt 12 điều kỷ luật khi quan hệ với nhân dân và chế độ sinh hoạt, học tập, công tác trong ngày, trong tuần của chiến sĩ.', 'Góp phần nâng cao ý thức chấp hành pháp luật nhà nước, kỷ luật quân đội, xây dựng đơn vị vững mạnh toàn diện mẫu mực, tiêu biểu.', '### 1. 12 ĐIỀU KỶ LUẬT KHI QUAN HỆ VỚI NHÂN DÂN
Kỷ luật sắt của quân đội bắt nguồn từ tính chất quân đội nhân dân: "Từ nhân dân mà ra, vì nhân dân mà phục vụ".
1. Không lấy của dân một cây kim, sợi chỉ; mua bán công bằng, mượn gì phải trả, làm hỏng phải đền.
2. Không cưỡng ép nhân dân, không quấy nhiễu, không xúc phạm đến danh dự, tự do tín ngưỡng, phong tục tập quán của nhân dân.
3. Tích cực tuyên truyền, vận động và cùng nhân dân thực hiện tốt mọi chủ trương của Đảng.

### 2. CHẾ ĐỘ SINH HOẠT VÀ NỀN NẾP CHÍNH QUY
* Chấp hành nghiêm giờ giấc báo thức, thể dục, điểm danh quân số, học tập huấn luyện theo kế hoạch.
* Lễ tiết tác phong quân nhân nghiêm chỉnh.
* Quản lý chặt chẽ vũ khí trang bị được giao.', 'document', 15, true, '2026-07-10T23:59:59Z', 'Dễ', '["Kỷ luật Quân đội","Điều lệnh quản lý bộ đội","Trực ban"]'::jsonb, '["Điều lệnh Quản lý bộ đội Quân đội nhân dân Việt Nam","Thông tư 143/2020/TT-BQP"]'::jsonb, '00000000-0000-4000-8000-000000000003', '2026-06-18T10:00:00Z', '2026-06-18T10:00:00Z', NULL, NULL, '[]'::jsonb, '[]'::jsonb);
INSERT INTO learning_topics (id, title, category, description, objective, content, content_type, estimated_minutes, required, deadline, difficulty, tags, references_data, created_by, created_at, updated_at, video_url, pdf_url, assigned_unit_ids, assigned_user_ids) VALUES ('t4', 'Công tác dân vận trong tình hình mới', 'Công tác Đảng, công tác chính trị', 'Vai trò, nhiệm vụ công tác dân vận của lực lượng vũ trang nhân dân địa phương nhằm củng cố khối đại đoàn kết toàn dân và thế trận lòng dân vững chắc.', 'Hiểu rõ phương châm ''Dân biết, dân bàn, dân làm, dân kiểm tra, dân giám sát, dân thụ hưởng'' và cách áp dụng vào thực tiễn địa phương.', '### 1. KHÁI NIỆM VÀ PHƯƠNG CHÂM DÂN VẬN
Dân vận là vận động tất cả lực lượng của mỗi một người dân để thực hành những chính sách của Đảng và Chính phủ.

### 2. PHƯƠNG CHÂM 6 CHỮ TRONG TÌNH HÌNH MỚI
* **Dân biết:** Thông tin minh bạch các chủ trương chính sách đến người dân.
* **Dân bàn:** Tổ chức họp dân thảo luận, lấy ý kiến đóng góp thiết thực.
* **Dân làm:** Huy động sức dân đồng lòng đóng góp công sức xây dựng quê hương.
* **Dân kiểm tra:** Giám sát quy trình thực hiện, đảm bảo công khai không tham nhũng.
* **Dân giám sát:** Theo dõi hiệu quả của công việc.
* **Dân thụ hưởng:** Thành quả phát triển phải phục vụ trực tiếp cho đời sống người dân.', 'document', 15, false, NULL, 'Dễ', '["Công tác dân vận","Tư tưởng Hồ Chí Minh","Vận động quần chúng"]'::jsonb, '["Quyết định số 290-QĐ/TW của Ban Chấp hành Trung ương","Nghị quyết số 25-NQ/TW"]'::jsonb, '00000000-0000-4000-8000-000000000003', '2026-06-20T08:00:00Z', '2026-06-20T08:00:00Z', NULL, NULL, '[]'::jsonb, '[]'::jsonb);
INSERT INTO learning_topics (id, title, category, description, objective, content, content_type, estimated_minutes, required, deadline, difficulty, tags, references_data, created_by, created_at, updated_at, video_url, pdf_url, assigned_unit_ids, assigned_user_ids) VALUES ('t5', 'Phòng chống thông tin xấu độc trên không gian mạng', 'Thời sự chính trị', 'Nhận diện các âm mưu thủ đoạn phá hoại tư tưởng trên không gian mạng, trang bị kỹ năng chọn lọc thông tin lành mạnh cho chiến sĩ.', 'Tăng cường sức đề kháng trước luận điệu xuyên tạc, bôi nhọ của các thế lực phản động, xây dựng văn hóa ứng xử lành mạnh trên mạng xã hội.', '### 1. THỦ ĐOẠN PHÁ HOẠI TƯ TƯỞNG
Các thế lực thù địch thường xuyên lập ra hàng ngàn tài khoản giả mạo, các trang blog vô danh để:
* Cắt ghép, xuyên tạc lịch sử Việt Nam, bôi nhọ lãnh tụ.
* Phóng đại các vấn đề tiêu cực xã hội để quy chụp bản chất chế độ.
* Kích động biểu tình, gây rối an ninh trật tự.

### 2. QUY TẮC "3 KHÔNG, 3 NÊN"
* **3 KHÔNG:** Không chia sẻ tin xấu độc; Không bình luận thô tục kích động; Không tham gia nhóm phản động.
* **3 NÊN:** Nên theo dõi tin chính thống; Nên lan tỏa hình ảnh đẹp bộ đội Cụ Hồ; Nên chủ động đấu tranh phản bác lịch thiệp.', 'document', 20, true, '2026-07-15T23:59:59Z', 'Khó', '["An ninh mạng","Thông tin xấu độc","Đấu tranh tư tưởng"]'::jsonb, '["Luật An ninh mạng năm 2018","Bộ Quy tắc ứng xử trên mạng xã hội"]'::jsonb, '00000000-0000-4000-8000-000000000003', '2026-06-22T14:00:00Z', '2026-06-22T14:00:00Z', NULL, NULL, '[]'::jsonb, '[]'::jsonb);
INSERT INTO learning_topics (id, title, category, description, objective, content, content_type, estimated_minutes, required, deadline, difficulty, tags, references_data, created_by, created_at, updated_at, video_url, pdf_url, assigned_unit_ids, assigned_user_ids) VALUES ('t6', 'Truyền thống lực lượng vũ trang địa phương', 'Giáo dục chính trị', 'Tìm hiểu lịch sử anh dũng, các chiến công tiêu biểu của lực lượng vũ trang nhân dân tỉnh, huyện và xã Yên Thế qua các thời kỳ.', 'Khơi dậy niềm tự hào dân tộc, truyền thống quê hương cách mạng, củng cố ý chí quyết tâm phấn đấu học tập, rèn luyện của cán bộ chiến sĩ.', '### LỊCH SỬ HÌNH THÀNH VÀ CHIẾN CÔNG TIÊU BIỂU
Lực lượng vũ trang địa phương xã Yên Thế được hình thành từ phong trào kháng chiến chống thực dân Pháp xâm lược.
* **Trận đánh đồn Phố Lèo:** Tiêu diệt và bắt sống hơn 50 tên địch, thu giữ nhiều vũ khí.
* **Phong trào toàn dân kháng chiến:** Xây dựng làng kháng chiến liên hoàn, chế tạo vũ khí thô sơ.

Trong thời kỳ chống Mỹ, hàng ngàn người con ưu tú hăng hái lên đường nhập ngũ, lực lượng dân quân tại chỗ bắn rơi máy bay Mỹ phá hoại.', 'document', 15, false, NULL, 'Dễ', '["Lịch sử truyền thống","Lực lượng địa phương","Du kích"]'::jsonb, '["Lịch sử Lực lượng vũ trang nhân dân huyện Yên Thế"]'::jsonb, '00000000-0000-4000-8000-000000000003', '2026-06-10T08:00:00Z', '2026-06-10T08:00:00Z', NULL, NULL, '[]'::jsonb, '[]'::jsonb);
INSERT INTO learning_topics (id, title, category, description, objective, content, content_type, estimated_minutes, required, deadline, difficulty, tags, references_data, created_by, created_at, updated_at, video_url, pdf_url, assigned_unit_ids, assigned_user_ids) VALUES ('t7', 'Luật Dân quân tự vệ năm 2019', 'Phổ biến giáo dục pháp luật', 'Phổ biến các quy định cốt lõi của Luật Dân quân tự vệ 2019 về vị trí, chức năng, nhiệm vụ, độ tuổi và thời hạn tham gia dân quân tự vệ.', 'Nắm vững nghĩa vụ tham gia dân quân tự vệ, chế độ chính sách được hưởng và trách nhiệm bảo vệ địa bàn.', '### 1. VỊ TRÍ, CHỨC NĂNG CỦA LỰC LƯỢNG DÂN QUÂN TỰ VỆ
Dân quân tự vệ là lực lượng vũ trang quần chúng không thoát ly sản xuất, đặt dưới sự lãnh đạo của Đảng.

### 2. ĐỘ TUỔI VÀ THỜI HẠN THAM GIA
* **Độ tuổi tham gia:** Nam từ đủ 18 tuổi đến hết 45 tuổi; nữ từ đủ 18 tuổi đến hết 40 tuổi.
* **Thời hạn thực hiện nghĩa vụ:** 4 năm.

### 3. NHIỆM VỤ CỦA DÂN QUÂN TỰ VỆ
* Sẵn sàng chiến đấu bảo vệ địa phương.
* Giữ gìn an ninh chính trị, trật tự an toàn xã hội.
* Khắc phục thiên tai, dịch bệnh, tìm kiếm cứu nạn.', 'document', 18, true, '2026-07-20T23:59:59Z', 'Trung bình', '["Dân quân tự vệ","Luật Dân quân tự vệ 2019","Pháp luật quốc phòng"]'::jsonb, '["Luật Dân quân tự vệ năm 2019","Nghị định 02/2020/NĐ-CP"]'::jsonb, '00000000-0000-4000-8000-000000000003', '2026-06-14T09:00:00Z', '2026-06-14T09:00:00Z', NULL, NULL, '[]'::jsonb, '[]'::jsonb);
INSERT INTO learning_topics (id, title, category, description, objective, content, content_type, estimated_minutes, required, deadline, difficulty, tags, references_data, created_by, created_at, updated_at, video_url, pdf_url, assigned_unit_ids, assigned_user_ids) VALUES ('t8', 'Chế độ chính trị nước Cộng hòa xã hội chủ nghĩa Việt Nam', 'Giáo dục chính trị', 'Tìm hiểu vị trí lãnh đạo của Đảng, vai trò quản lý của Nhà nước và quyền làm chủ của nhân dân theo Hiến pháp 2013.', 'Xây dựng nhận thức đúng đắn về hệ thống chính trị Việt Nam, củng cố niềm tin vào sự lãnh đạo của Đảng.', '### 1. BẢN CHẤT CỦA NHÀ NƯỚC TA
Nhà nước Cộng hòa xã hội chủ nghĩa Việt Nam là nhà nước pháp quyền xã hội chủ nghĩa của Nhân dân, do Nhân dân, vì Nhân dân.

### 2. VAI TRÒ LÃNH ĐẠO CỦA ĐẢNG
Đảng Cộng sản Việt Nam là lực lượng lãnh đạo Nhà nước và xã hội (quy định tại Điều 4 Hiến pháp 2013).

### 3. QUYỀN LÀM CHỦ CỦA NHÂN DÂN
Tất cả quyền lực nhà nước thuộc về Nhân dân mà nền tảng là liên minh giữa giai cấp công nhân với giai cấp nông dân và đội ngũ trí thức.', 'document', 15, false, NULL, 'Trung bình', '["Hiến pháp","Hệ thống chính trị","Đảng lãnh đạo"]'::jsonb, '["Hiến pháp nước Cộng hòa xã hội chủ nghĩa Việt Nam năm 2013"]'::jsonb, '00000000-0000-4000-8000-000000000003', '2026-06-16T08:00:00Z', '2026-06-16T08:00:00Z', NULL, NULL, '[]'::jsonb, '[]'::jsonb);
INSERT INTO learning_topics (id, title, category, description, objective, content, content_type, estimated_minutes, required, deadline, difficulty, tags, references_data, created_by, created_at, updated_at, video_url, pdf_url, assigned_unit_ids, assigned_user_ids) VALUES ('t9', 'Xây dựng nền quốc phòng toàn dân vững mạnh', 'Giáo dục chính trị', 'Quan điểm chỉ đạo của Đảng về xây dựng nền quốc phòng toàn dân gắn với thế trận an ninh nhân dân vững mạnh toàn diện.', 'Giúp chiến sĩ hiểu rõ trách nhiệm của địa phương trong xây dựng khu vực phòng thủ, thế trận quốc phòng toàn dân.', '### 1. KHÁI NIỆM QUỐC PHÒNG TOÀN DÂN
Quốc phòng toàn dân là nền quốc phòng mang tính chất "vì dân, của dân, do dân", phát triển theo hướng toàn dân, toàn diện, độc lập tự chủ.

### 2. NỘI DUNG XÂY DỰNG NỀN QUỐC PHÒNG
* Xây dựng tiềm lực chính trị - tinh thần vững chắc.
* Xây dựng tiềm lực kinh tế, khoa học công nghệ quốc phòng.
* Xây dựng tiềm lực quân sự thực lực mạnh mẽ.

### 3. THẾ TRẬN QUỐC PHÒNG TOÀN DÂN
Phân chia khu vực phòng thủ then chốt, kết hợp phát triển kinh tế xã hội với củng cố quốc phòng an ninh tại địa bàn cơ sở.', 'document', 20, false, NULL, 'Khó', '["Quốc phòng toàn dân","Khu vực phòng thủ","An ninh nhân dân"]'::jsonb, '["Luật Quốc phòng năm 2018","Sách trắng Quốc phòng Việt Nam 2019"]'::jsonb, '00000000-0000-4000-8000-000000000003', '2026-06-18T15:00:00Z', '2026-06-18T15:00:00Z', NULL, NULL, '[]'::jsonb, '[]'::jsonb);
INSERT INTO learning_topics (id, title, category, description, objective, content, content_type, estimated_minutes, required, deadline, difficulty, tags, references_data, created_by, created_at, updated_at, video_url, pdf_url, assigned_unit_ids, assigned_user_ids) VALUES ('t10', 'Thông tư 143/2020/TT-BQP về xử lý kỷ luật quân đội', 'Quy định điều lệnh', 'Phổ biến chi tiết các hình thức kỷ luật đối với quân nhân vi phạm nề nếp kỷ luật, tác phong quân đội.', 'Răn đe, giáo dục chiến sĩ giữ gìn tác phong chuẩn mực, không vi phạm pháp luật và quy chế đơn vị.', '### 1. PHẠM VI ÁP DỤNG
Thông tư áp dụng đối với quân nhân, công nhân quốc phòng, viên chức quốc phòng và lực lượng dân quân tự vệ khi thực hiện nhiệm vụ.

### 2. CÁC HÌNH THỨC KỶ LUẬT CHÍNH
* **Đối với sĩ quan, quân nhân chuyên nghiệp:** Khiển trách, cảnh cáo, hạ bậc lương, giáng chức, cách chức, tước quân hàm quân nhân chuyên nghiệp, tước danh hiệu quân nhân.
* **Đối với hạ sĩ quan, chiến sĩ:** Khiển trách, cảnh cáo, giáng cấp bậc quân hàm, giáng chức, cách chức, tước danh hiệu quân nhân.
* **Đối với dân quân tự vệ:** Tước danh hiệu dân quân tự vệ, cảnh cáo, khiển trách.

### 3. NGUYÊN TẮC XỬ LÝ
Kịp thời, nghiêm minh, chính xác, khách quan, đúng thẩm quyền và đúng pháp luật.', 'document', 15, true, '2026-07-25T23:59:59Z', 'Trung bình', '["Thông tư 143","Xử lý kỷ luật","Kỷ luật Quân đội"]'::jsonb, '["Thông tư 143/2020/TT-BQP của Bộ Quốc phòng"]'::jsonb, '00000000-0000-4000-8000-000000000003', '2026-06-21T09:00:00Z', '2026-06-21T09:00:00Z', NULL, NULL, '[]'::jsonb, '[]'::jsonb);

-- -----------------------------------------------------
-- SEEDING LEARNING SECTIONS
-- -----------------------------------------------------
INSERT INTO learning_sections (id, topic_id, title, content, section_order, required) VALUES ('sec_t1_1', 't1', 'Phần 1: Khái niệm, vai trò và ý nghĩa cốt lõi', 'Nội dung phần 1 tập trung giới thiệu bối cảnh lịch sử, ý nghĩa quan trọng và vai trò thực tiễn của bài học "Giáo dục chính trị: Kiên định mục tiêu lý tưởng cách mạng" đối với sự nghiệp xây dựng bảo vệ Tổ quốc.', 1, true);
INSERT INTO learning_sections (id, topic_id, title, content, section_order, required) VALUES ('sec_t1_2', 't1', 'Phần 2: Các nội dung trọng tâm và văn bản quy phạm liên quan', 'Phân tích sâu các văn bản quy định của Đảng, Nhà nước, Bộ Quốc phòng, hoặc các lý thuyết lý luận của chuyên đề "Giáo dục chính trị: Kiên định mục tiêu lý tưởng cách mạng".', 2, true);
INSERT INTO learning_sections (id, topic_id, title, content, section_order, required) VALUES ('sec_t1_3', 't1', 'Phần 3: Trách nhiệm và hành động thực tiễn tại đơn vị cơ sở', 'Xác định rõ vai trò trách nhiệm của bản thân cán bộ, chiến sĩ tại Ban CHQS xã Yên Thế và các tổ dân quân địa phương trong việc học tập, chấp hành lý luận bài học "Giáo dục chính trị: Kiên định mục tiêu lý tưởng cách mạng".', 3, false);
INSERT INTO learning_sections (id, topic_id, title, content, section_order, required) VALUES ('sec_t2_1', 't2', 'Phần 1: Khái niệm, vai trò và ý nghĩa cốt lõi', 'Nội dung phần 1 tập trung giới thiệu bối cảnh lịch sử, ý nghĩa quan trọng và vai trò thực tiễn của bài học "Phổ biến giáo dục pháp luật: Nghĩa vụ quân sự và trách nhiệm công dân" đối với sự nghiệp xây dựng bảo vệ Tổ quốc.', 1, true);
INSERT INTO learning_sections (id, topic_id, title, content, section_order, required) VALUES ('sec_t2_2', 't2', 'Phần 2: Các nội dung trọng tâm và văn bản quy phạm liên quan', 'Phân tích sâu các văn bản quy định của Đảng, Nhà nước, Bộ Quốc phòng, hoặc các lý thuyết lý luận của chuyên đề "Phổ biến giáo dục pháp luật: Nghĩa vụ quân sự và trách nhiệm công dân".', 2, true);
INSERT INTO learning_sections (id, topic_id, title, content, section_order, required) VALUES ('sec_t2_3', 't2', 'Phần 3: Trách nhiệm và hành động thực tiễn tại đơn vị cơ sở', 'Xác định rõ vai trò trách nhiệm của bản thân cán bộ, chiến sĩ tại Ban CHQS xã Yên Thế và các tổ dân quân địa phương trong việc học tập, chấp hành lý luận bài học "Phổ biến giáo dục pháp luật: Nghĩa vụ quân sự và trách nhiệm công dân".', 3, false);
INSERT INTO learning_sections (id, topic_id, title, content, section_order, required) VALUES ('sec_t3_1', 't3', 'Phần 1: Khái niệm, vai trò và ý nghĩa cốt lõi', 'Nội dung phần 1 tập trung giới thiệu bối cảnh lịch sử, ý nghĩa quan trọng và vai trò thực tiễn của bài học "Kỷ luật Quân đội và nền nếp chính quy" đối với sự nghiệp xây dựng bảo vệ Tổ quốc.', 1, true);
INSERT INTO learning_sections (id, topic_id, title, content, section_order, required) VALUES ('sec_t3_2', 't3', 'Phần 2: Các nội dung trọng tâm và văn bản quy phạm liên quan', 'Phân tích sâu các văn bản quy định của Đảng, Nhà nước, Bộ Quốc phòng, hoặc các lý thuyết lý luận của chuyên đề "Kỷ luật Quân đội và nền nếp chính quy".', 2, true);
INSERT INTO learning_sections (id, topic_id, title, content, section_order, required) VALUES ('sec_t3_3', 't3', 'Phần 3: Trách nhiệm và hành động thực tiễn tại đơn vị cơ sở', 'Xác định rõ vai trò trách nhiệm của bản thân cán bộ, chiến sĩ tại Ban CHQS xã Yên Thế và các tổ dân quân địa phương trong việc học tập, chấp hành lý luận bài học "Kỷ luật Quân đội và nền nếp chính quy".', 3, false);
INSERT INTO learning_sections (id, topic_id, title, content, section_order, required) VALUES ('sec_t4_1', 't4', 'Phần 1: Khái niệm, vai trò và ý nghĩa cốt lõi', 'Nội dung phần 1 tập trung giới thiệu bối cảnh lịch sử, ý nghĩa quan trọng và vai trò thực tiễn của bài học "Công tác dân vận trong tình hình mới" đối với sự nghiệp xây dựng bảo vệ Tổ quốc.', 1, true);
INSERT INTO learning_sections (id, topic_id, title, content, section_order, required) VALUES ('sec_t4_2', 't4', 'Phần 2: Các nội dung trọng tâm và văn bản quy phạm liên quan', 'Phân tích sâu các văn bản quy định của Đảng, Nhà nước, Bộ Quốc phòng, hoặc các lý thuyết lý luận của chuyên đề "Công tác dân vận trong tình hình mới".', 2, true);
INSERT INTO learning_sections (id, topic_id, title, content, section_order, required) VALUES ('sec_t4_3', 't4', 'Phần 3: Trách nhiệm và hành động thực tiễn tại đơn vị cơ sở', 'Xác định rõ vai trò trách nhiệm của bản thân cán bộ, chiến sĩ tại Ban CHQS xã Yên Thế và các tổ dân quân địa phương trong việc học tập, chấp hành lý luận bài học "Công tác dân vận trong tình hình mới".', 3, false);
INSERT INTO learning_sections (id, topic_id, title, content, section_order, required) VALUES ('sec_t5_1', 't5', 'Phần 1: Khái niệm, vai trò và ý nghĩa cốt lõi', 'Nội dung phần 1 tập trung giới thiệu bối cảnh lịch sử, ý nghĩa quan trọng và vai trò thực tiễn của bài học "Phòng chống thông tin xấu độc trên không gian mạng" đối với sự nghiệp xây dựng bảo vệ Tổ quốc.', 1, true);
INSERT INTO learning_sections (id, topic_id, title, content, section_order, required) VALUES ('sec_t5_2', 't5', 'Phần 2: Các nội dung trọng tâm và văn bản quy phạm liên quan', 'Phân tích sâu các văn bản quy định của Đảng, Nhà nước, Bộ Quốc phòng, hoặc các lý thuyết lý luận của chuyên đề "Phòng chống thông tin xấu độc trên không gian mạng".', 2, true);
INSERT INTO learning_sections (id, topic_id, title, content, section_order, required) VALUES ('sec_t5_3', 't5', 'Phần 3: Trách nhiệm và hành động thực tiễn tại đơn vị cơ sở', 'Xác định rõ vai trò trách nhiệm của bản thân cán bộ, chiến sĩ tại Ban CHQS xã Yên Thế và các tổ dân quân địa phương trong việc học tập, chấp hành lý luận bài học "Phòng chống thông tin xấu độc trên không gian mạng".', 3, false);
INSERT INTO learning_sections (id, topic_id, title, content, section_order, required) VALUES ('sec_t6_1', 't6', 'Phần 1: Khái niệm, vai trò và ý nghĩa cốt lõi', 'Nội dung phần 1 tập trung giới thiệu bối cảnh lịch sử, ý nghĩa quan trọng và vai trò thực tiễn của bài học "Truyền thống lực lượng vũ trang địa phương" đối với sự nghiệp xây dựng bảo vệ Tổ quốc.', 1, true);
INSERT INTO learning_sections (id, topic_id, title, content, section_order, required) VALUES ('sec_t6_2', 't6', 'Phần 2: Các nội dung trọng tâm và văn bản quy phạm liên quan', 'Phân tích sâu các văn bản quy định của Đảng, Nhà nước, Bộ Quốc phòng, hoặc các lý thuyết lý luận của chuyên đề "Truyền thống lực lượng vũ trang địa phương".', 2, true);
INSERT INTO learning_sections (id, topic_id, title, content, section_order, required) VALUES ('sec_t6_3', 't6', 'Phần 3: Trách nhiệm và hành động thực tiễn tại đơn vị cơ sở', 'Xác định rõ vai trò trách nhiệm của bản thân cán bộ, chiến sĩ tại Ban CHQS xã Yên Thế và các tổ dân quân địa phương trong việc học tập, chấp hành lý luận bài học "Truyền thống lực lượng vũ trang địa phương".', 3, false);
INSERT INTO learning_sections (id, topic_id, title, content, section_order, required) VALUES ('sec_t7_1', 't7', 'Phần 1: Khái niệm, vai trò và ý nghĩa cốt lõi', 'Nội dung phần 1 tập trung giới thiệu bối cảnh lịch sử, ý nghĩa quan trọng và vai trò thực tiễn của bài học "Luật Dân quân tự vệ năm 2019" đối với sự nghiệp xây dựng bảo vệ Tổ quốc.', 1, true);
INSERT INTO learning_sections (id, topic_id, title, content, section_order, required) VALUES ('sec_t7_2', 't7', 'Phần 2: Các nội dung trọng tâm và văn bản quy phạm liên quan', 'Phân tích sâu các văn bản quy định của Đảng, Nhà nước, Bộ Quốc phòng, hoặc các lý thuyết lý luận của chuyên đề "Luật Dân quân tự vệ năm 2019".', 2, true);
INSERT INTO learning_sections (id, topic_id, title, content, section_order, required) VALUES ('sec_t7_3', 't7', 'Phần 3: Trách nhiệm và hành động thực tiễn tại đơn vị cơ sở', 'Xác định rõ vai trò trách nhiệm của bản thân cán bộ, chiến sĩ tại Ban CHQS xã Yên Thế và các tổ dân quân địa phương trong việc học tập, chấp hành lý luận bài học "Luật Dân quân tự vệ năm 2019".', 3, false);
INSERT INTO learning_sections (id, topic_id, title, content, section_order, required) VALUES ('sec_t8_1', 't8', 'Phần 1: Khái niệm, vai trò và ý nghĩa cốt lõi', 'Nội dung phần 1 tập trung giới thiệu bối cảnh lịch sử, ý nghĩa quan trọng và vai trò thực tiễn của bài học "Chế độ chính trị nước Cộng hòa xã hội chủ nghĩa Việt Nam" đối với sự nghiệp xây dựng bảo vệ Tổ quốc.', 1, true);
INSERT INTO learning_sections (id, topic_id, title, content, section_order, required) VALUES ('sec_t8_2', 't8', 'Phần 2: Các nội dung trọng tâm và văn bản quy phạm liên quan', 'Phân tích sâu các văn bản quy định của Đảng, Nhà nước, Bộ Quốc phòng, hoặc các lý thuyết lý luận của chuyên đề "Chế độ chính trị nước Cộng hòa xã hội chủ nghĩa Việt Nam".', 2, true);
INSERT INTO learning_sections (id, topic_id, title, content, section_order, required) VALUES ('sec_t8_3', 't8', 'Phần 3: Trách nhiệm và hành động thực tiễn tại đơn vị cơ sở', 'Xác định rõ vai trò trách nhiệm của bản thân cán bộ, chiến sĩ tại Ban CHQS xã Yên Thế và các tổ dân quân địa phương trong việc học tập, chấp hành lý luận bài học "Chế độ chính trị nước Cộng hòa xã hội chủ nghĩa Việt Nam".', 3, false);
INSERT INTO learning_sections (id, topic_id, title, content, section_order, required) VALUES ('sec_t9_1', 't9', 'Phần 1: Khái niệm, vai trò và ý nghĩa cốt lõi', 'Nội dung phần 1 tập trung giới thiệu bối cảnh lịch sử, ý nghĩa quan trọng và vai trò thực tiễn của bài học "Xây dựng nền quốc phòng toàn dân vững mạnh" đối với sự nghiệp xây dựng bảo vệ Tổ quốc.', 1, true);
INSERT INTO learning_sections (id, topic_id, title, content, section_order, required) VALUES ('sec_t9_2', 't9', 'Phần 2: Các nội dung trọng tâm và văn bản quy phạm liên quan', 'Phân tích sâu các văn bản quy định của Đảng, Nhà nước, Bộ Quốc phòng, hoặc các lý thuyết lý luận của chuyên đề "Xây dựng nền quốc phòng toàn dân vững mạnh".', 2, true);
INSERT INTO learning_sections (id, topic_id, title, content, section_order, required) VALUES ('sec_t9_3', 't9', 'Phần 3: Trách nhiệm và hành động thực tiễn tại đơn vị cơ sở', 'Xác định rõ vai trò trách nhiệm của bản thân cán bộ, chiến sĩ tại Ban CHQS xã Yên Thế và các tổ dân quân địa phương trong việc học tập, chấp hành lý luận bài học "Xây dựng nền quốc phòng toàn dân vững mạnh".', 3, false);
INSERT INTO learning_sections (id, topic_id, title, content, section_order, required) VALUES ('sec_t10_1', 't10', 'Phần 1: Khái niệm, vai trò và ý nghĩa cốt lõi', 'Nội dung phần 1 tập trung giới thiệu bối cảnh lịch sử, ý nghĩa quan trọng và vai trò thực tiễn của bài học "Thông tư 143/2020/TT-BQP về xử lý kỷ luật quân đội" đối với sự nghiệp xây dựng bảo vệ Tổ quốc.', 1, true);
INSERT INTO learning_sections (id, topic_id, title, content, section_order, required) VALUES ('sec_t10_2', 't10', 'Phần 2: Các nội dung trọng tâm và văn bản quy phạm liên quan', 'Phân tích sâu các văn bản quy định của Đảng, Nhà nước, Bộ Quốc phòng, hoặc các lý thuyết lý luận của chuyên đề "Thông tư 143/2020/TT-BQP về xử lý kỷ luật quân đội".', 2, true);
INSERT INTO learning_sections (id, topic_id, title, content, section_order, required) VALUES ('sec_t10_3', 't10', 'Phần 3: Trách nhiệm và hành động thực tiễn tại đơn vị cơ sở', 'Xác định rõ vai trò trách nhiệm của bản thân cán bộ, chiến sĩ tại Ban CHQS xã Yên Thế và các tổ dân quân địa phương trong việc học tập, chấp hành lý luận bài học "Thông tư 143/2020/TT-BQP về xử lý kỷ luật quân đội".', 3, false);

-- -----------------------------------------------------
-- SEEDING LEARNING ASSIGNMENTS
-- -----------------------------------------------------
INSERT INTO learning_assignments (id, topic_id, assigned_to_user_id, assigned_to_unit_id, assigned_by, required, deadline, status, created_at, updated_at) VALUES ('assign_1', 't1', NULL, '10000000-0000-4000-8000-000000000002', '00000000-0000-4000-8000-000000000003', true, '2026-07-05T23:59:59Z', 'pending', '2026-06-20T08:00:00Z', '2026-06-20T08:00:00Z');
INSERT INTO learning_assignments (id, topic_id, assigned_to_user_id, assigned_to_unit_id, assigned_by, required, deadline, status, created_at, updated_at) VALUES ('assign_2', 't2', NULL, '10000000-0000-4000-8000-000000000003', '00000000-0000-4000-8000-000000000003', true, '2026-07-01T23:59:59Z', 'pending', '2026-06-15T09:00:00Z', '2026-06-15T09:00:00Z');

-- -----------------------------------------------------
-- SEEDING LEARNING PROGRESS
-- -----------------------------------------------------
INSERT INTO learning_progress (id, user_id, topic_id, status, progress_percent, started_at, completed_at, last_accessed_at, need_review, score_impact) VALUES ('p1_mem1', '00000000-0000-4000-8000-000000000004', 't1', 'completed', 100, '2026-06-16T08:30:00Z', '2026-06-16T09:10:00Z', '2026-06-16T09:10:00Z', false, NULL);
INSERT INTO learning_progress (id, user_id, topic_id, status, progress_percent, started_at, completed_at, last_accessed_at, need_review, score_impact) VALUES ('p2_mem1', '00000000-0000-4000-8000-000000000004', 't2', 'in_progress', 60, '2026-06-18T14:00:00Z', NULL, '2026-06-25T11:30:00Z', false, NULL);
INSERT INTO learning_progress (id, user_id, topic_id, status, progress_percent, started_at, completed_at, last_accessed_at, need_review, score_impact) VALUES ('p3_mem1', '00000000-0000-4000-8000-000000000004', 't3', 'not_started', 0, '2026-06-18T00:00:00Z', NULL, '2026-06-18T00:00:00Z', false, NULL);
INSERT INTO learning_progress (id, user_id, topic_id, status, progress_percent, started_at, completed_at, last_accessed_at, need_review, score_impact) VALUES ('p5_mem1', '00000000-0000-4000-8000-000000000004', 't5', 'need_review', 100, '2026-06-23T09:00:00Z', '2026-06-23T09:30:00Z', '2026-06-23T09:45:00Z', true, NULL);
INSERT INTO learning_progress (id, user_id, topic_id, status, progress_percent, started_at, completed_at, last_accessed_at, need_review, score_impact) VALUES ('p1_mem2', '00000000-0000-4000-8000-000000000004', 't1', 'in_progress', 40, '2026-06-20T10:00:00Z', NULL, '2026-06-22T15:20:00Z', false, NULL);
INSERT INTO learning_progress (id, user_id, topic_id, status, progress_percent, started_at, completed_at, last_accessed_at, need_review, score_impact) VALUES ('p2_mem2', '00000000-0000-4000-8000-000000000004', 't2', 'completed', 100, '2026-06-15T09:00:00Z', '2026-06-15T09:40:00Z', '2026-06-15T09:40:00Z', false, NULL);

-- -----------------------------------------------------
-- SEEDING QUESTIONS
-- -----------------------------------------------------
INSERT INTO questions (id, topic_id, type, question_text, options, correct_answers, explanation, difficulty, reference_info, tags) VALUES ('q1_1', 't1', 'single', 'Nền tảng tư tưởng, kim chỉ nam hành động của Đảng Cộng sản Việt Nam và Cách mạng Việt Nam là gì?', '["Chủ nghĩa thực dụng và lý thuyết khoa học hiện đại.","Chủ nghĩa Mác - Lênin và Tư tưởng Hồ Chí Minh.","Truyền thống yêu nước và bản sắc văn hóa dân tộc đơn thuần.","Kinh nghiệm cách mạng của các nước phương Tây."]'::jsonb, '[1]'::jsonb, 'Chủ nghĩa Mác - Lênin và Tư tưởng Hồ Chí Minh là nền tảng tư tưởng, kim chỉ nam hành động đã được khẳng định rõ trong Cương lĩnh của Đảng.', 'Dễ', 'Hiến pháp 2013', '["Chính trị","Lập trường tư tưởng"]'::jsonb);
INSERT INTO questions (id, topic_id, type, question_text, options, correct_answers, explanation, difficulty, reference_info, tags) VALUES ('q1_2', 't1', 'true_false', 'Lực lượng dân quân tự vệ là lực lượng vũ trang quần chúng thoát ly khỏi mọi hoạt động sản xuất, công tác của địa phương để tập trung huấn luyện chiến đấu toàn thời gian trong thời bình.', '["Đúng","Sai"]'::jsonb, '[1]'::jsonb, 'Dân quân tự vệ là lực lượng vũ trang quần chúng không thoát ly sản xuất, công tác.', 'Dễ', 'Điều 2 Luật Dân quân tự vệ 2019', '["Dân quân tự vệ","Điều lệnh"]'::jsonb);
INSERT INTO questions (id, topic_id, type, question_text, options, correct_answers, explanation, difficulty, reference_info, tags) VALUES ('q1_3', 't1', 'multiple', 'Nội dung cốt lõi của lý tưởng cách mạng Việt Nam bao gồm những yếu tố nào dưới đây? (Chọn tất cả đáp án đúng)', '["Kiên định mục tiêu độc lập dân tộc và chủ nghĩa xã hội.","Tăng cường chạy đua vũ trang với các quốc gia láng giềng.","Trung thành vô hạn với Tổ quốc và Nhân dân.","Đặt lợi ích cá nhân lên trên lợi ích quốc gia dân tộc."]'::jsonb, '[0,2]'::jsonb, 'Lý tưởng cách mạng luôn kiên định mục tiêu độc lập dân tộc và chủ nghĩa xã hội.', 'Trung bình', 'Tài liệu học tập chính trị', '["Chính trị","Lý tưởng"]'::jsonb);
INSERT INTO questions (id, topic_id, type, question_text, options, correct_answers, explanation, difficulty, reference_info, tags) VALUES ('q1_4', 't1', 'single', 'Để giữ vững lập trường tư tưởng trước thông tin xuyên tạc, chiến sĩ dân quân cần tránh hành vi nào?', '["Học tập chính trị nghiêm túc.","Tin tưởng sự lãnh đạo của Đảng.","Chia sẻ các thông tin giật gân, chưa kiểm chứng trên mạng xã hội.","Đọc báo Quân đội nhân dân chính thống."]'::jsonb, '[2]'::jsonb, 'Tuyệt đối không chia sẻ tin tức chưa kiểm chứng.', 'Trung bình', 'Quy chế đơn vị', '["An ninh mạng"]'::jsonb);
INSERT INTO questions (id, topic_id, type, question_text, options, correct_answers, explanation, difficulty, reference_info, tags) VALUES ('q1_5', 't1', 'single', 'Nghị quyết Đại hội XIII của Đảng xác định mục tiêu phát triển đất nước đến năm 2045 là gì?', '["Trở thành nước đang phát triển, có công nghiệp theo hướng hiện đại.","Trở thành nước phát triển, thu nhập cao, theo định hướng xã hội chủ nghĩa.","Trở thành nền kinh tế lớn nhất thế giới.","Hoàn thành công nghiệp hóa hiện đại hóa sơ bộ."]'::jsonb, '[1]'::jsonb, 'Nghị quyết xác định tầm nhìn đến năm 2045 trở thành nước phát triển, thu nhập cao theo định hướng XHCN.', 'Khó', 'Nghị quyết Đại hội XIII', '["Đại hội XIII","Nghị quyết"]'::jsonb);
INSERT INTO questions (id, topic_id, type, question_text, options, correct_answers, explanation, difficulty, reference_info, tags) VALUES ('q2_1', 't2', 'single', 'Theo Luật Nghĩa vụ quân sự 2015, độ tuổi gọi nhập ngũ bình thường của công dân nam trong thời bình là bao nhiêu?', '["Từ đủ 18 tuổi đến hết 22 tuổi.","Từ đủ 18 tuổi đến hết 25 tuổi.","Từ đủ 17 tuổi đến hết 25 tuổi.","Từ đủ 18 tuổi đến hết 30 tuổi."]'::jsonb, '[1]'::jsonb, 'Độ tuổi gọi nhập ngũ từ đủ 18 tuổi đến hết 25 tuổi; nếu học đại học/cao đẳng được tạm hoãn thì đến hết 27 tuổi.', 'Dễ', 'Luật Nghĩa vụ quân sự 2015', '["NVQS","Độ tuổi"]'::jsonb);
INSERT INTO questions (id, topic_id, type, question_text, options, correct_answers, explanation, difficulty, reference_info, tags) VALUES ('q2_2', 't2', 'single', 'Thời hạn phục vụ tại ngũ trong thời bình của hạ sĩ quan, binh sĩ Quân đội nhân dân Việt Nam là bao nhiêu tháng?', '["12 tháng.","18 tháng.","24 tháng.","36 tháng."]'::jsonb, '[2]'::jsonb, 'Thời hạn phục vụ tại ngũ trong thời bình là 24 tháng.', 'Dễ', 'Điều 21 Luật Nghĩa vụ quân sự 2015', '["NVQS"]'::jsonb);
INSERT INTO questions (id, topic_id, type, question_text, options, correct_answers, explanation, difficulty, reference_info, tags) VALUES ('q2_3', 't2', 'scenario', 'Anh Nam đang là sinh viên học hệ chính quy tại một trường Đại học. Anh nhận được Lệnh gọi khám sức khỏe nghĩa vụ quân sự. Theo pháp luật hiện hành, anh Nam xử lý như thế nào là đúng nhất?', '["Tự ý xé lệnh gọi vì cho rằng mình là sinh viên đương nhiên được miễn.","Cần chấp hành đi khám sức khỏe theo lệnh gọi, đồng thời nộp Giấy xác nhận học tập cho Ban CHQS xã để làm thủ tục xin tạm hoãn gọi nhập ngũ.","Nhờ người khác đi khám thay mình.","Trốn tránh không đến điểm khám và không nộp giấy tờ gì."]'::jsonb, '[1]'::jsonb, 'Công dân phải chấp hành lệnh gọi khám tuyển, việc tạm hoãn sẽ được xem xét dựa trên hồ sơ hợp lệ.', 'Trung bình', 'Luật NVQS 2015', '["Tình huống","NVQS"]'::jsonb);
INSERT INTO questions (id, topic_id, type, question_text, options, correct_answers, explanation, difficulty, reference_info, tags) VALUES ('q2_4', 't2', 'true_false', 'Hành vi trốn tránh lệnh gọi nhập ngũ sau khi đã bị phạt hành chính vẫn chỉ bị phạt tiền tiếp tục mà không bao giờ bị truy cứu trách nhiệm hình sự.', '["Đúng","Sai"]'::jsonb, '[1]'::jsonb, 'Hành vi trốn tránh sau khi đã bị phạt hành chính có thể bị truy cứu trách nhiệm hình sự theo Điều 332 Bộ luật Hình sự.', 'Trung bình', 'Bộ luật Hình sự', '["Pháp luật","Xử phạt"]'::jsonb);
INSERT INTO questions (id, topic_id, type, question_text, options, correct_answers, explanation, difficulty, reference_info, tags) VALUES ('q2_5', 't2', 'multiple', 'Những đối tượng nào sau đây được miễn gọi nhập ngũ trong thời bình? (Chọn tất cả đáp án đúng)', '["Con của liệt sĩ, con của thương binh hạng một.","Tất cả công dân nam là lao động tự do tại địa phương.","Một anh hoặc một em ruột của liệt sĩ.","Công dân nam đang học đại học chính quy."]'::jsonb, '[0,3]'::jsonb, NULL, NULL, NULL, '[]'::jsonb);
INSERT INTO questions (id, topic_id, type, question_text, options, correct_answers, explanation, difficulty, reference_info, tags) VALUES ('q3_extra_1', 't3', 'single', 'Câu hỏi khảo sát kiến thức chuyên đề nâng cao về "Kỷ luật Quân đội và nền nếp chính quy" - Câu số 1?', '["Đáp án A: Cần nghiêm túc tiếp thu thực hiện","Đáp án B: Không cần thiết áp dụng","Đáp án C: Tùy tình hình thực tế đơn vị","Đáp án D: Do cấp trên quyết định"]'::jsonb, '[0]'::jsonb, 'Giải thích: Đây là câu hỏi khảo thí chính trị tiêu chuẩn. Người học cần nắm vững và kiên định lý luận chính trị chính quy.', 'Trung bình', 'Điều lệnh Quản lý bộ đội Quân đội nhân dân Việt Nam', '["Huấn luyện","Lý luận chính trị","Tự luận"]'::jsonb);
INSERT INTO questions (id, topic_id, type, question_text, options, correct_answers, explanation, difficulty, reference_info, tags) VALUES ('q3_extra_2', 't3', 'true_false', 'Câu hỏi khảo sát kiến thức chuyên đề nâng cao về "Kỷ luật Quân đội và nền nếp chính quy" - Câu số 2?', '["Đúng, hoàn toàn đồng ý","Sai, chưa chính xác"]'::jsonb, '[0]'::jsonb, 'Giải thích: Đây là câu hỏi khảo thí chính trị tiêu chuẩn. Người học cần nắm vững và kiên định lý luận chính trị chính quy.', 'Trung bình', 'Điều lệnh Quản lý bộ đội Quân đội nhân dân Việt Nam', '["Huấn luyện","Lý luận chính trị","Tự luận"]'::jsonb);
INSERT INTO questions (id, topic_id, type, question_text, options, correct_answers, explanation, difficulty, reference_info, tags) VALUES ('q3_extra_3', 't3', 'single', 'Câu hỏi khảo sát kiến thức chuyên đề nâng cao về "Kỷ luật Quân đội và nền nếp chính quy" - Câu số 3?', '["Đáp án A: Cần nghiêm túc tiếp thu thực hiện","Đáp án B: Không cần thiết áp dụng","Đáp án C: Tùy tình hình thực tế đơn vị","Đáp án D: Do cấp trên quyết định"]'::jsonb, '[0]'::jsonb, 'Giải thích: Đây là câu hỏi khảo thí chính trị tiêu chuẩn. Người học cần nắm vững và kiên định lý luận chính trị chính quy.', 'Trung bình', 'Điều lệnh Quản lý bộ đội Quân đội nhân dân Việt Nam', '["Huấn luyện","Lý luận chính trị","Tự luận"]'::jsonb);
INSERT INTO questions (id, topic_id, type, question_text, options, correct_answers, explanation, difficulty, reference_info, tags) VALUES ('q3_extra_4', 't3', 'true_false', 'Câu hỏi khảo sát kiến thức chuyên đề nâng cao về "Kỷ luật Quân đội và nền nếp chính quy" - Câu số 4?', '["Đúng, hoàn toàn đồng ý","Sai, chưa chính xác"]'::jsonb, '[0]'::jsonb, 'Giải thích: Đây là câu hỏi khảo thí chính trị tiêu chuẩn. Người học cần nắm vững và kiên định lý luận chính trị chính quy.', 'Trung bình', 'Điều lệnh Quản lý bộ đội Quân đội nhân dân Việt Nam', '["Huấn luyện","Lý luận chính trị","Tự luận"]'::jsonb);
INSERT INTO questions (id, topic_id, type, question_text, options, correct_answers, explanation, difficulty, reference_info, tags) VALUES ('q3_extra_5', 't3', 'single', 'Câu hỏi khảo sát kiến thức chuyên đề nâng cao về "Kỷ luật Quân đội và nền nếp chính quy" - Câu số 5?', '["Đáp án A: Cần nghiêm túc tiếp thu thực hiện","Đáp án B: Không cần thiết áp dụng","Đáp án C: Tùy tình hình thực tế đơn vị","Đáp án D: Do cấp trên quyết định"]'::jsonb, '[0]'::jsonb, 'Giải thích: Đây là câu hỏi khảo thí chính trị tiêu chuẩn. Người học cần nắm vững và kiên định lý luận chính trị chính quy.', 'Trung bình', 'Điều lệnh Quản lý bộ đội Quân đội nhân dân Việt Nam', '["Huấn luyện","Lý luận chính trị","Tự luận"]'::jsonb);
INSERT INTO questions (id, topic_id, type, question_text, options, correct_answers, explanation, difficulty, reference_info, tags) VALUES ('q4_extra_1', 't4', 'single', 'Câu hỏi khảo sát kiến thức chuyên đề nâng cao về "Công tác dân vận trong tình hình mới" - Câu số 1?', '["Đáp án A: Cần nghiêm túc tiếp thu thực hiện","Đáp án B: Không cần thiết áp dụng","Đáp án C: Tùy tình hình thực tế đơn vị","Đáp án D: Do cấp trên quyết định"]'::jsonb, '[0]'::jsonb, 'Giải thích: Đây là câu hỏi khảo thí chính trị tiêu chuẩn. Người học cần nắm vững và kiên định lý luận chính trị chính quy.', 'Trung bình', 'Quyết định số 290-QĐ/TW của Ban Chấp hành Trung ương', '["Huấn luyện","Lý luận chính trị","Tự luận"]'::jsonb);
INSERT INTO questions (id, topic_id, type, question_text, options, correct_answers, explanation, difficulty, reference_info, tags) VALUES ('q4_extra_2', 't4', 'true_false', 'Câu hỏi khảo sát kiến thức chuyên đề nâng cao về "Công tác dân vận trong tình hình mới" - Câu số 2?', '["Đúng, hoàn toàn đồng ý","Sai, chưa chính xác"]'::jsonb, '[0]'::jsonb, 'Giải thích: Đây là câu hỏi khảo thí chính trị tiêu chuẩn. Người học cần nắm vững và kiên định lý luận chính trị chính quy.', 'Trung bình', 'Quyết định số 290-QĐ/TW của Ban Chấp hành Trung ương', '["Huấn luyện","Lý luận chính trị","Tự luận"]'::jsonb);
INSERT INTO questions (id, topic_id, type, question_text, options, correct_answers, explanation, difficulty, reference_info, tags) VALUES ('q4_extra_3', 't4', 'single', 'Câu hỏi khảo sát kiến thức chuyên đề nâng cao về "Công tác dân vận trong tình hình mới" - Câu số 3?', '["Đáp án A: Cần nghiêm túc tiếp thu thực hiện","Đáp án B: Không cần thiết áp dụng","Đáp án C: Tùy tình hình thực tế đơn vị","Đáp án D: Do cấp trên quyết định"]'::jsonb, '[0]'::jsonb, 'Giải thích: Đây là câu hỏi khảo thí chính trị tiêu chuẩn. Người học cần nắm vững và kiên định lý luận chính trị chính quy.', 'Trung bình', 'Quyết định số 290-QĐ/TW của Ban Chấp hành Trung ương', '["Huấn luyện","Lý luận chính trị","Tự luận"]'::jsonb);
INSERT INTO questions (id, topic_id, type, question_text, options, correct_answers, explanation, difficulty, reference_info, tags) VALUES ('q4_extra_4', 't4', 'true_false', 'Câu hỏi khảo sát kiến thức chuyên đề nâng cao về "Công tác dân vận trong tình hình mới" - Câu số 4?', '["Đúng, hoàn toàn đồng ý","Sai, chưa chính xác"]'::jsonb, '[0]'::jsonb, 'Giải thích: Đây là câu hỏi khảo thí chính trị tiêu chuẩn. Người học cần nắm vững và kiên định lý luận chính trị chính quy.', 'Trung bình', 'Quyết định số 290-QĐ/TW của Ban Chấp hành Trung ương', '["Huấn luyện","Lý luận chính trị","Tự luận"]'::jsonb);
INSERT INTO questions (id, topic_id, type, question_text, options, correct_answers, explanation, difficulty, reference_info, tags) VALUES ('q4_extra_5', 't4', 'single', 'Câu hỏi khảo sát kiến thức chuyên đề nâng cao về "Công tác dân vận trong tình hình mới" - Câu số 5?', '["Đáp án A: Cần nghiêm túc tiếp thu thực hiện","Đáp án B: Không cần thiết áp dụng","Đáp án C: Tùy tình hình thực tế đơn vị","Đáp án D: Do cấp trên quyết định"]'::jsonb, '[0]'::jsonb, 'Giải thích: Đây là câu hỏi khảo thí chính trị tiêu chuẩn. Người học cần nắm vững và kiên định lý luận chính trị chính quy.', 'Trung bình', 'Quyết định số 290-QĐ/TW của Ban Chấp hành Trung ương', '["Huấn luyện","Lý luận chính trị","Tự luận"]'::jsonb);
INSERT INTO questions (id, topic_id, type, question_text, options, correct_answers, explanation, difficulty, reference_info, tags) VALUES ('q5_extra_1', 't5', 'single', 'Câu hỏi khảo sát kiến thức chuyên đề nâng cao về "Phòng chống thông tin xấu độc trên không gian mạng" - Câu số 1?', '["Đáp án A: Cần nghiêm túc tiếp thu thực hiện","Đáp án B: Không cần thiết áp dụng","Đáp án C: Tùy tình hình thực tế đơn vị","Đáp án D: Do cấp trên quyết định"]'::jsonb, '[0]'::jsonb, 'Giải thích: Đây là câu hỏi khảo thí chính trị tiêu chuẩn. Người học cần nắm vững và kiên định lý luận chính trị chính quy.', 'Trung bình', 'Luật An ninh mạng năm 2018', '["Huấn luyện","Lý luận chính trị","Tự luận"]'::jsonb);
INSERT INTO questions (id, topic_id, type, question_text, options, correct_answers, explanation, difficulty, reference_info, tags) VALUES ('q5_extra_2', 't5', 'true_false', 'Câu hỏi khảo sát kiến thức chuyên đề nâng cao về "Phòng chống thông tin xấu độc trên không gian mạng" - Câu số 2?', '["Đúng, hoàn toàn đồng ý","Sai, chưa chính xác"]'::jsonb, '[0]'::jsonb, 'Giải thích: Đây là câu hỏi khảo thí chính trị tiêu chuẩn. Người học cần nắm vững và kiên định lý luận chính trị chính quy.', 'Trung bình', 'Luật An ninh mạng năm 2018', '["Huấn luyện","Lý luận chính trị","Tự luận"]'::jsonb);
INSERT INTO questions (id, topic_id, type, question_text, options, correct_answers, explanation, difficulty, reference_info, tags) VALUES ('q5_extra_3', 't5', 'single', 'Câu hỏi khảo sát kiến thức chuyên đề nâng cao về "Phòng chống thông tin xấu độc trên không gian mạng" - Câu số 3?', '["Đáp án A: Cần nghiêm túc tiếp thu thực hiện","Đáp án B: Không cần thiết áp dụng","Đáp án C: Tùy tình hình thực tế đơn vị","Đáp án D: Do cấp trên quyết định"]'::jsonb, '[0]'::jsonb, 'Giải thích: Đây là câu hỏi khảo thí chính trị tiêu chuẩn. Người học cần nắm vững và kiên định lý luận chính trị chính quy.', 'Trung bình', 'Luật An ninh mạng năm 2018', '["Huấn luyện","Lý luận chính trị","Tự luận"]'::jsonb);
INSERT INTO questions (id, topic_id, type, question_text, options, correct_answers, explanation, difficulty, reference_info, tags) VALUES ('q5_extra_4', 't5', 'true_false', 'Câu hỏi khảo sát kiến thức chuyên đề nâng cao về "Phòng chống thông tin xấu độc trên không gian mạng" - Câu số 4?', '["Đúng, hoàn toàn đồng ý","Sai, chưa chính xác"]'::jsonb, '[0]'::jsonb, 'Giải thích: Đây là câu hỏi khảo thí chính trị tiêu chuẩn. Người học cần nắm vững và kiên định lý luận chính trị chính quy.', 'Trung bình', 'Luật An ninh mạng năm 2018', '["Huấn luyện","Lý luận chính trị","Tự luận"]'::jsonb);
INSERT INTO questions (id, topic_id, type, question_text, options, correct_answers, explanation, difficulty, reference_info, tags) VALUES ('q5_extra_5', 't5', 'single', 'Câu hỏi khảo sát kiến thức chuyên đề nâng cao về "Phòng chống thông tin xấu độc trên không gian mạng" - Câu số 5?', '["Đáp án A: Cần nghiêm túc tiếp thu thực hiện","Đáp án B: Không cần thiết áp dụng","Đáp án C: Tùy tình hình thực tế đơn vị","Đáp án D: Do cấp trên quyết định"]'::jsonb, '[0]'::jsonb, 'Giải thích: Đây là câu hỏi khảo thí chính trị tiêu chuẩn. Người học cần nắm vững và kiên định lý luận chính trị chính quy.', 'Trung bình', 'Luật An ninh mạng năm 2018', '["Huấn luyện","Lý luận chính trị","Tự luận"]'::jsonb);
INSERT INTO questions (id, topic_id, type, question_text, options, correct_answers, explanation, difficulty, reference_info, tags) VALUES ('q6_extra_1', 't6', 'single', 'Câu hỏi khảo sát kiến thức chuyên đề nâng cao về "Truyền thống lực lượng vũ trang địa phương" - Câu số 1?', '["Đáp án A: Cần nghiêm túc tiếp thu thực hiện","Đáp án B: Không cần thiết áp dụng","Đáp án C: Tùy tình hình thực tế đơn vị","Đáp án D: Do cấp trên quyết định"]'::jsonb, '[0]'::jsonb, 'Giải thích: Đây là câu hỏi khảo thí chính trị tiêu chuẩn. Người học cần nắm vững và kiên định lý luận chính trị chính quy.', 'Trung bình', 'Lịch sử Lực lượng vũ trang nhân dân huyện Yên Thế', '["Huấn luyện","Lý luận chính trị","Tự luận"]'::jsonb);
INSERT INTO questions (id, topic_id, type, question_text, options, correct_answers, explanation, difficulty, reference_info, tags) VALUES ('q6_extra_2', 't6', 'true_false', 'Câu hỏi khảo sát kiến thức chuyên đề nâng cao về "Truyền thống lực lượng vũ trang địa phương" - Câu số 2?', '["Đúng, hoàn toàn đồng ý","Sai, chưa chính xác"]'::jsonb, '[0]'::jsonb, 'Giải thích: Đây là câu hỏi khảo thí chính trị tiêu chuẩn. Người học cần nắm vững và kiên định lý luận chính trị chính quy.', 'Trung bình', 'Lịch sử Lực lượng vũ trang nhân dân huyện Yên Thế', '["Huấn luyện","Lý luận chính trị","Tự luận"]'::jsonb);
INSERT INTO questions (id, topic_id, type, question_text, options, correct_answers, explanation, difficulty, reference_info, tags) VALUES ('q6_extra_3', 't6', 'single', 'Câu hỏi khảo sát kiến thức chuyên đề nâng cao về "Truyền thống lực lượng vũ trang địa phương" - Câu số 3?', '["Đáp án A: Cần nghiêm túc tiếp thu thực hiện","Đáp án B: Không cần thiết áp dụng","Đáp án C: Tùy tình hình thực tế đơn vị","Đáp án D: Do cấp trên quyết định"]'::jsonb, '[0]'::jsonb, 'Giải thích: Đây là câu hỏi khảo thí chính trị tiêu chuẩn. Người học cần nắm vững và kiên định lý luận chính trị chính quy.', 'Trung bình', 'Lịch sử Lực lượng vũ trang nhân dân huyện Yên Thế', '["Huấn luyện","Lý luận chính trị","Tự luận"]'::jsonb);
INSERT INTO questions (id, topic_id, type, question_text, options, correct_answers, explanation, difficulty, reference_info, tags) VALUES ('q6_extra_4', 't6', 'true_false', 'Câu hỏi khảo sát kiến thức chuyên đề nâng cao về "Truyền thống lực lượng vũ trang địa phương" - Câu số 4?', '["Đúng, hoàn toàn đồng ý","Sai, chưa chính xác"]'::jsonb, '[0]'::jsonb, 'Giải thích: Đây là câu hỏi khảo thí chính trị tiêu chuẩn. Người học cần nắm vững và kiên định lý luận chính trị chính quy.', 'Trung bình', 'Lịch sử Lực lượng vũ trang nhân dân huyện Yên Thế', '["Huấn luyện","Lý luận chính trị","Tự luận"]'::jsonb);
INSERT INTO questions (id, topic_id, type, question_text, options, correct_answers, explanation, difficulty, reference_info, tags) VALUES ('q6_extra_5', 't6', 'single', 'Câu hỏi khảo sát kiến thức chuyên đề nâng cao về "Truyền thống lực lượng vũ trang địa phương" - Câu số 5?', '["Đáp án A: Cần nghiêm túc tiếp thu thực hiện","Đáp án B: Không cần thiết áp dụng","Đáp án C: Tùy tình hình thực tế đơn vị","Đáp án D: Do cấp trên quyết định"]'::jsonb, '[0]'::jsonb, 'Giải thích: Đây là câu hỏi khảo thí chính trị tiêu chuẩn. Người học cần nắm vững và kiên định lý luận chính trị chính quy.', 'Trung bình', 'Lịch sử Lực lượng vũ trang nhân dân huyện Yên Thế', '["Huấn luyện","Lý luận chính trị","Tự luận"]'::jsonb);
INSERT INTO questions (id, topic_id, type, question_text, options, correct_answers, explanation, difficulty, reference_info, tags) VALUES ('q7_extra_1', 't7', 'single', 'Câu hỏi khảo sát kiến thức chuyên đề nâng cao về "Luật Dân quân tự vệ năm 2019" - Câu số 1?', '["Đáp án A: Cần nghiêm túc tiếp thu thực hiện","Đáp án B: Không cần thiết áp dụng","Đáp án C: Tùy tình hình thực tế đơn vị","Đáp án D: Do cấp trên quyết định"]'::jsonb, '[0]'::jsonb, 'Giải thích: Đây là câu hỏi khảo thí chính trị tiêu chuẩn. Người học cần nắm vững và kiên định lý luận chính trị chính quy.', 'Trung bình', 'Luật Dân quân tự vệ năm 2019', '["Huấn luyện","Lý luận chính trị","Tự luận"]'::jsonb);
INSERT INTO questions (id, topic_id, type, question_text, options, correct_answers, explanation, difficulty, reference_info, tags) VALUES ('q7_extra_2', 't7', 'true_false', 'Câu hỏi khảo sát kiến thức chuyên đề nâng cao về "Luật Dân quân tự vệ năm 2019" - Câu số 2?', '["Đúng, hoàn toàn đồng ý","Sai, chưa chính xác"]'::jsonb, '[0]'::jsonb, 'Giải thích: Đây là câu hỏi khảo thí chính trị tiêu chuẩn. Người học cần nắm vững và kiên định lý luận chính trị chính quy.', 'Trung bình', 'Luật Dân quân tự vệ năm 2019', '["Huấn luyện","Lý luận chính trị","Tự luận"]'::jsonb);
INSERT INTO questions (id, topic_id, type, question_text, options, correct_answers, explanation, difficulty, reference_info, tags) VALUES ('q7_extra_3', 't7', 'single', 'Câu hỏi khảo sát kiến thức chuyên đề nâng cao về "Luật Dân quân tự vệ năm 2019" - Câu số 3?', '["Đáp án A: Cần nghiêm túc tiếp thu thực hiện","Đáp án B: Không cần thiết áp dụng","Đáp án C: Tùy tình hình thực tế đơn vị","Đáp án D: Do cấp trên quyết định"]'::jsonb, '[0]'::jsonb, 'Giải thích: Đây là câu hỏi khảo thí chính trị tiêu chuẩn. Người học cần nắm vững và kiên định lý luận chính trị chính quy.', 'Trung bình', 'Luật Dân quân tự vệ năm 2019', '["Huấn luyện","Lý luận chính trị","Tự luận"]'::jsonb);
INSERT INTO questions (id, topic_id, type, question_text, options, correct_answers, explanation, difficulty, reference_info, tags) VALUES ('q7_extra_4', 't7', 'true_false', 'Câu hỏi khảo sát kiến thức chuyên đề nâng cao về "Luật Dân quân tự vệ năm 2019" - Câu số 4?', '["Đúng, hoàn toàn đồng ý","Sai, chưa chính xác"]'::jsonb, '[0]'::jsonb, 'Giải thích: Đây là câu hỏi khảo thí chính trị tiêu chuẩn. Người học cần nắm vững và kiên định lý luận chính trị chính quy.', 'Trung bình', 'Luật Dân quân tự vệ năm 2019', '["Huấn luyện","Lý luận chính trị","Tự luận"]'::jsonb);
INSERT INTO questions (id, topic_id, type, question_text, options, correct_answers, explanation, difficulty, reference_info, tags) VALUES ('q7_extra_5', 't7', 'single', 'Câu hỏi khảo sát kiến thức chuyên đề nâng cao về "Luật Dân quân tự vệ năm 2019" - Câu số 5?', '["Đáp án A: Cần nghiêm túc tiếp thu thực hiện","Đáp án B: Không cần thiết áp dụng","Đáp án C: Tùy tình hình thực tế đơn vị","Đáp án D: Do cấp trên quyết định"]'::jsonb, '[0]'::jsonb, 'Giải thích: Đây là câu hỏi khảo thí chính trị tiêu chuẩn. Người học cần nắm vững và kiên định lý luận chính trị chính quy.', 'Trung bình', 'Luật Dân quân tự vệ năm 2019', '["Huấn luyện","Lý luận chính trị","Tự luận"]'::jsonb);
INSERT INTO questions (id, topic_id, type, question_text, options, correct_answers, explanation, difficulty, reference_info, tags) VALUES ('q8_extra_1', 't8', 'single', 'Câu hỏi khảo sát kiến thức chuyên đề nâng cao về "Chế độ chính trị nước Cộng hòa xã hội chủ nghĩa Việt Nam" - Câu số 1?', '["Đáp án A: Cần nghiêm túc tiếp thu thực hiện","Đáp án B: Không cần thiết áp dụng","Đáp án C: Tùy tình hình thực tế đơn vị","Đáp án D: Do cấp trên quyết định"]'::jsonb, '[0]'::jsonb, 'Giải thích: Đây là câu hỏi khảo thí chính trị tiêu chuẩn. Người học cần nắm vững và kiên định lý luận chính trị chính quy.', 'Trung bình', 'Hiến pháp nước Cộng hòa xã hội chủ nghĩa Việt Nam năm 2013', '["Huấn luyện","Lý luận chính trị","Tự luận"]'::jsonb);
INSERT INTO questions (id, topic_id, type, question_text, options, correct_answers, explanation, difficulty, reference_info, tags) VALUES ('q8_extra_2', 't8', 'true_false', 'Câu hỏi khảo sát kiến thức chuyên đề nâng cao về "Chế độ chính trị nước Cộng hòa xã hội chủ nghĩa Việt Nam" - Câu số 2?', '["Đúng, hoàn toàn đồng ý","Sai, chưa chính xác"]'::jsonb, '[0]'::jsonb, 'Giải thích: Đây là câu hỏi khảo thí chính trị tiêu chuẩn. Người học cần nắm vững và kiên định lý luận chính trị chính quy.', 'Trung bình', 'Hiến pháp nước Cộng hòa xã hội chủ nghĩa Việt Nam năm 2013', '["Huấn luyện","Lý luận chính trị","Tự luận"]'::jsonb);
INSERT INTO questions (id, topic_id, type, question_text, options, correct_answers, explanation, difficulty, reference_info, tags) VALUES ('q8_extra_3', 't8', 'single', 'Câu hỏi khảo sát kiến thức chuyên đề nâng cao về "Chế độ chính trị nước Cộng hòa xã hội chủ nghĩa Việt Nam" - Câu số 3?', '["Đáp án A: Cần nghiêm túc tiếp thu thực hiện","Đáp án B: Không cần thiết áp dụng","Đáp án C: Tùy tình hình thực tế đơn vị","Đáp án D: Do cấp trên quyết định"]'::jsonb, '[0]'::jsonb, 'Giải thích: Đây là câu hỏi khảo thí chính trị tiêu chuẩn. Người học cần nắm vững và kiên định lý luận chính trị chính quy.', 'Trung bình', 'Hiến pháp nước Cộng hòa xã hội chủ nghĩa Việt Nam năm 2013', '["Huấn luyện","Lý luận chính trị","Tự luận"]'::jsonb);
INSERT INTO questions (id, topic_id, type, question_text, options, correct_answers, explanation, difficulty, reference_info, tags) VALUES ('q8_extra_4', 't8', 'true_false', 'Câu hỏi khảo sát kiến thức chuyên đề nâng cao về "Chế độ chính trị nước Cộng hòa xã hội chủ nghĩa Việt Nam" - Câu số 4?', '["Đúng, hoàn toàn đồng ý","Sai, chưa chính xác"]'::jsonb, '[0]'::jsonb, 'Giải thích: Đây là câu hỏi khảo thí chính trị tiêu chuẩn. Người học cần nắm vững và kiên định lý luận chính trị chính quy.', 'Trung bình', 'Hiến pháp nước Cộng hòa xã hội chủ nghĩa Việt Nam năm 2013', '["Huấn luyện","Lý luận chính trị","Tự luận"]'::jsonb);
INSERT INTO questions (id, topic_id, type, question_text, options, correct_answers, explanation, difficulty, reference_info, tags) VALUES ('q8_extra_5', 't8', 'single', 'Câu hỏi khảo sát kiến thức chuyên đề nâng cao về "Chế độ chính trị nước Cộng hòa xã hội chủ nghĩa Việt Nam" - Câu số 5?', '["Đáp án A: Cần nghiêm túc tiếp thu thực hiện","Đáp án B: Không cần thiết áp dụng","Đáp án C: Tùy tình hình thực tế đơn vị","Đáp án D: Do cấp trên quyết định"]'::jsonb, '[0]'::jsonb, 'Giải thích: Đây là câu hỏi khảo thí chính trị tiêu chuẩn. Người học cần nắm vững và kiên định lý luận chính trị chính quy.', 'Trung bình', 'Hiến pháp nước Cộng hòa xã hội chủ nghĩa Việt Nam năm 2013', '["Huấn luyện","Lý luận chính trị","Tự luận"]'::jsonb);
INSERT INTO questions (id, topic_id, type, question_text, options, correct_answers, explanation, difficulty, reference_info, tags) VALUES ('q9_extra_1', 't9', 'single', 'Câu hỏi khảo sát kiến thức chuyên đề nâng cao về "Xây dựng nền quốc phòng toàn dân vững mạnh" - Câu số 1?', '["Đáp án A: Cần nghiêm túc tiếp thu thực hiện","Đáp án B: Không cần thiết áp dụng","Đáp án C: Tùy tình hình thực tế đơn vị","Đáp án D: Do cấp trên quyết định"]'::jsonb, '[0]'::jsonb, 'Giải thích: Đây là câu hỏi khảo thí chính trị tiêu chuẩn. Người học cần nắm vững và kiên định lý luận chính trị chính quy.', 'Trung bình', 'Luật Quốc phòng năm 2018', '["Huấn luyện","Lý luận chính trị","Tự luận"]'::jsonb);
INSERT INTO questions (id, topic_id, type, question_text, options, correct_answers, explanation, difficulty, reference_info, tags) VALUES ('q9_extra_2', 't9', 'true_false', 'Câu hỏi khảo sát kiến thức chuyên đề nâng cao về "Xây dựng nền quốc phòng toàn dân vững mạnh" - Câu số 2?', '["Đúng, hoàn toàn đồng ý","Sai, chưa chính xác"]'::jsonb, '[0]'::jsonb, 'Giải thích: Đây là câu hỏi khảo thí chính trị tiêu chuẩn. Người học cần nắm vững và kiên định lý luận chính trị chính quy.', 'Trung bình', 'Luật Quốc phòng năm 2018', '["Huấn luyện","Lý luận chính trị","Tự luận"]'::jsonb);
INSERT INTO questions (id, topic_id, type, question_text, options, correct_answers, explanation, difficulty, reference_info, tags) VALUES ('q9_extra_3', 't9', 'single', 'Câu hỏi khảo sát kiến thức chuyên đề nâng cao về "Xây dựng nền quốc phòng toàn dân vững mạnh" - Câu số 3?', '["Đáp án A: Cần nghiêm túc tiếp thu thực hiện","Đáp án B: Không cần thiết áp dụng","Đáp án C: Tùy tình hình thực tế đơn vị","Đáp án D: Do cấp trên quyết định"]'::jsonb, '[0]'::jsonb, 'Giải thích: Đây là câu hỏi khảo thí chính trị tiêu chuẩn. Người học cần nắm vững và kiên định lý luận chính trị chính quy.', 'Trung bình', 'Luật Quốc phòng năm 2018', '["Huấn luyện","Lý luận chính trị","Tự luận"]'::jsonb);
INSERT INTO questions (id, topic_id, type, question_text, options, correct_answers, explanation, difficulty, reference_info, tags) VALUES ('q9_extra_4', 't9', 'true_false', 'Câu hỏi khảo sát kiến thức chuyên đề nâng cao về "Xây dựng nền quốc phòng toàn dân vững mạnh" - Câu số 4?', '["Đúng, hoàn toàn đồng ý","Sai, chưa chính xác"]'::jsonb, '[0]'::jsonb, 'Giải thích: Đây là câu hỏi khảo thí chính trị tiêu chuẩn. Người học cần nắm vững và kiên định lý luận chính trị chính quy.', 'Trung bình', 'Luật Quốc phòng năm 2018', '["Huấn luyện","Lý luận chính trị","Tự luận"]'::jsonb);
INSERT INTO questions (id, topic_id, type, question_text, options, correct_answers, explanation, difficulty, reference_info, tags) VALUES ('q9_extra_5', 't9', 'single', 'Câu hỏi khảo sát kiến thức chuyên đề nâng cao về "Xây dựng nền quốc phòng toàn dân vững mạnh" - Câu số 5?', '["Đáp án A: Cần nghiêm túc tiếp thu thực hiện","Đáp án B: Không cần thiết áp dụng","Đáp án C: Tùy tình hình thực tế đơn vị","Đáp án D: Do cấp trên quyết định"]'::jsonb, '[0]'::jsonb, 'Giải thích: Đây là câu hỏi khảo thí chính trị tiêu chuẩn. Người học cần nắm vững và kiên định lý luận chính trị chính quy.', 'Trung bình', 'Luật Quốc phòng năm 2018', '["Huấn luyện","Lý luận chính trị","Tự luận"]'::jsonb);
INSERT INTO questions (id, topic_id, type, question_text, options, correct_answers, explanation, difficulty, reference_info, tags) VALUES ('q10_extra_1', 't10', 'single', 'Câu hỏi khảo sát kiến thức chuyên đề nâng cao về "Thông tư 143/2020/TT-BQP về xử lý kỷ luật quân đội" - Câu số 1?', '["Đáp án A: Cần nghiêm túc tiếp thu thực hiện","Đáp án B: Không cần thiết áp dụng","Đáp án C: Tùy tình hình thực tế đơn vị","Đáp án D: Do cấp trên quyết định"]'::jsonb, '[0]'::jsonb, 'Giải thích: Đây là câu hỏi khảo thí chính trị tiêu chuẩn. Người học cần nắm vững và kiên định lý luận chính trị chính quy.', 'Trung bình', 'Thông tư 143/2020/TT-BQP của Bộ Quốc phòng', '["Huấn luyện","Lý luận chính trị","Tự luận"]'::jsonb);
INSERT INTO questions (id, topic_id, type, question_text, options, correct_answers, explanation, difficulty, reference_info, tags) VALUES ('q10_extra_2', 't10', 'true_false', 'Câu hỏi khảo sát kiến thức chuyên đề nâng cao về "Thông tư 143/2020/TT-BQP về xử lý kỷ luật quân đội" - Câu số 2?', '["Đúng, hoàn toàn đồng ý","Sai, chưa chính xác"]'::jsonb, '[0]'::jsonb, 'Giải thích: Đây là câu hỏi khảo thí chính trị tiêu chuẩn. Người học cần nắm vững và kiên định lý luận chính trị chính quy.', 'Trung bình', 'Thông tư 143/2020/TT-BQP của Bộ Quốc phòng', '["Huấn luyện","Lý luận chính trị","Tự luận"]'::jsonb);
INSERT INTO questions (id, topic_id, type, question_text, options, correct_answers, explanation, difficulty, reference_info, tags) VALUES ('q10_extra_3', 't10', 'single', 'Câu hỏi khảo sát kiến thức chuyên đề nâng cao về "Thông tư 143/2020/TT-BQP về xử lý kỷ luật quân đội" - Câu số 3?', '["Đáp án A: Cần nghiêm túc tiếp thu thực hiện","Đáp án B: Không cần thiết áp dụng","Đáp án C: Tùy tình hình thực tế đơn vị","Đáp án D: Do cấp trên quyết định"]'::jsonb, '[0]'::jsonb, 'Giải thích: Đây là câu hỏi khảo thí chính trị tiêu chuẩn. Người học cần nắm vững và kiên định lý luận chính trị chính quy.', 'Trung bình', 'Thông tư 143/2020/TT-BQP của Bộ Quốc phòng', '["Huấn luyện","Lý luận chính trị","Tự luận"]'::jsonb);
INSERT INTO questions (id, topic_id, type, question_text, options, correct_answers, explanation, difficulty, reference_info, tags) VALUES ('q10_extra_4', 't10', 'true_false', 'Câu hỏi khảo sát kiến thức chuyên đề nâng cao về "Thông tư 143/2020/TT-BQP về xử lý kỷ luật quân đội" - Câu số 4?', '["Đúng, hoàn toàn đồng ý","Sai, chưa chính xác"]'::jsonb, '[0]'::jsonb, 'Giải thích: Đây là câu hỏi khảo thí chính trị tiêu chuẩn. Người học cần nắm vững và kiên định lý luận chính trị chính quy.', 'Trung bình', 'Thông tư 143/2020/TT-BQP của Bộ Quốc phòng', '["Huấn luyện","Lý luận chính trị","Tự luận"]'::jsonb);
INSERT INTO questions (id, topic_id, type, question_text, options, correct_answers, explanation, difficulty, reference_info, tags) VALUES ('q10_extra_5', 't10', 'single', 'Câu hỏi khảo sát kiến thức chuyên đề nâng cao về "Thông tư 143/2020/TT-BQP về xử lý kỷ luật quân đội" - Câu số 5?', '["Đáp án A: Cần nghiêm túc tiếp thu thực hiện","Đáp án B: Không cần thiết áp dụng","Đáp án C: Tùy tình hình thực tế đơn vị","Đáp án D: Do cấp trên quyết định"]'::jsonb, '[0]'::jsonb, 'Giải thích: Đây là câu hỏi khảo thí chính trị tiêu chuẩn. Người học cần nắm vững và kiên định lý luận chính trị chính quy.', 'Trung bình', 'Thông tư 143/2020/TT-BQP của Bộ Quốc phòng', '["Huấn luyện","Lý luận chính trị","Tự luận"]'::jsonb);

-- -----------------------------------------------------
-- SEEDING QUIZ ATTEMPTS
-- -----------------------------------------------------
INSERT INTO quiz_attempts (id, user_id, quiz_type, topic_id, started_at, submitted_at, score, correct_count, wrong_count, total_questions, answers, status) VALUES ('qa1', '00000000-0000-4000-8000-000000000004', 'topic', 't1', '2026-06-16T09:00:00Z', '2026-06-16T09:10:00Z', 10, 3, 0, 3, '{"q1_1":[1],"q1_2":[1],"q1_3":[0,2]}'::jsonb, 'submitted');
INSERT INTO quiz_attempts (id, user_id, quiz_type, topic_id, started_at, submitted_at, score, correct_count, wrong_count, total_questions, answers, status) VALUES ('qa2', '00000000-0000-4000-8000-000000000004', 'topic', 't5', '2026-06-23T09:35:00Z', '2026-06-23T09:45:00Z', 0, 0, 1, 1, '{"q5_1":[1,3]}'::jsonb, 'submitted');
INSERT INTO quiz_attempts (id, user_id, quiz_type, topic_id, started_at, submitted_at, score, correct_count, wrong_count, total_questions, answers, status) VALUES ('qa_3', '00000000-0000-4000-8000-000000000004', 'topic', 't1', '2026-06-24T09:32:54.294Z', '2026-06-24T09:42:54.294Z', 6, 3, 1, 3, '{"q1_1":[1],"q1_2":[1]}'::jsonb, 'submitted');
INSERT INTO quiz_attempts (id, user_id, quiz_type, topic_id, started_at, submitted_at, score, correct_count, wrong_count, total_questions, answers, status) VALUES ('qa_4', '00000000-0000-4000-8000-000000000004', 'topic', 't1', '2026-06-23T09:32:54.294Z', '2026-06-23T09:42:54.294Z', 8, 0, 1, 3, '{"q1_1":[1],"q1_2":[1]}'::jsonb, 'submitted');
INSERT INTO quiz_attempts (id, user_id, quiz_type, topic_id, started_at, submitted_at, score, correct_count, wrong_count, total_questions, answers, status) VALUES ('qa_5', '00000000-0000-4000-8000-000000000004', 'topic', 't1', '2026-06-22T09:32:54.294Z', '2026-06-22T09:42:54.294Z', 10, 1, 0, 3, '{"q1_1":[1],"q1_2":[1]}'::jsonb, 'submitted');
INSERT INTO quiz_attempts (id, user_id, quiz_type, topic_id, started_at, submitted_at, score, correct_count, wrong_count, total_questions, answers, status) VALUES ('qa_6', '00000000-0000-4000-8000-000000000004', 'topic', 't1', '2026-06-21T09:32:54.294Z', '2026-06-21T09:42:54.294Z', 1, 2, 2, 3, '{"q1_1":[1],"q1_2":[1]}'::jsonb, 'submitted');
INSERT INTO quiz_attempts (id, user_id, quiz_type, topic_id, started_at, submitted_at, score, correct_count, wrong_count, total_questions, answers, status) VALUES ('qa_7', '00000000-0000-4000-8000-000000000004', 'topic', 't1', '2026-06-20T09:32:54.294Z', '2026-06-20T09:42:54.294Z', 3, 3, 1, 3, '{"q1_1":[1],"q1_2":[1]}'::jsonb, 'submitted');
INSERT INTO quiz_attempts (id, user_id, quiz_type, topic_id, started_at, submitted_at, score, correct_count, wrong_count, total_questions, answers, status) VALUES ('qa_8', '00000000-0000-4000-8000-000000000004', 'topic', 't1', '2026-06-19T09:32:54.294Z', '2026-06-19T09:42:54.294Z', 5, 0, 1, 3, '{"q1_1":[1],"q1_2":[1]}'::jsonb, 'submitted');
INSERT INTO quiz_attempts (id, user_id, quiz_type, topic_id, started_at, submitted_at, score, correct_count, wrong_count, total_questions, answers, status) VALUES ('qa_9', '00000000-0000-4000-8000-000000000004', 'topic', 't1', '2026-06-18T09:32:54.294Z', '2026-06-18T09:42:54.294Z', 7, 1, 0, 3, '{"q1_1":[1],"q1_2":[1]}'::jsonb, 'submitted');
INSERT INTO quiz_attempts (id, user_id, quiz_type, topic_id, started_at, submitted_at, score, correct_count, wrong_count, total_questions, answers, status) VALUES ('qa_10', '00000000-0000-4000-8000-000000000004', 'topic', 't1', '2026-06-17T09:32:54.294Z', '2026-06-17T09:42:54.294Z', 9, 2, 2, 3, '{"q1_1":[1],"q1_2":[1]}'::jsonb, 'submitted');

-- -----------------------------------------------------
-- SEEDING EXAMS
-- -----------------------------------------------------
INSERT INTO exams (id, title, description, topic_ids, duration_minutes, question_count, start_date, end_date, passing_score, allow_review, status, lifecycle_status, created_by) VALUES ('e1', 'Kiểm tra trắc nghiệm Giáo dục chính trị & Pháp luật đợt 1 năm 2026', 'Kỳ thi đánh giá định kỳ bắt buộc đối với toàn bộ lực lượng dân quân tự vệ thuộc Ban CHQS xã Yên Thế nhằm kiểm tra nhận thức lý luận chính trị.', '["t1","t2"]'::jsonb, 15, 4, '2026-06-20T00:00:00Z', '2026-07-05T23:59:59Z', 5, true, 'active', 'published', '00000000-0000-4000-8000-000000000003');
INSERT INTO exams (id, title, description, topic_ids, duration_minutes, question_count, start_date, end_date, passing_score, allow_review, status, lifecycle_status, created_by) VALUES ('e2', 'Sát hạch quy định kỷ luật quân đội và điều lệnh quản lý bộ đội', 'Đánh giá mức độ am hiểu và chấp hành kỷ luật, nếp sống chính quy văn hóa quân sự.', '["t3","t10"]'::jsonb, 10, 4, '2026-06-22T00:00:00Z', '2026-07-15T23:59:59Z', 6, true, 'active', 'published', '00000000-0000-4000-8000-000000000003');
INSERT INTO exams (id, title, description, topic_ids, duration_minutes, question_count, start_date, end_date, passing_score, allow_review, status, lifecycle_status, created_by) VALUES ('e3', 'Thi tìm hiểu Luật Dân quân tự vệ và Luật Quốc phòng (Đã hết hạn)', 'Kỳ thi thử nghiệm nâng cao nhận thức luật chuyên ngành quốc phòng.', '["t7"]'::jsonb, 20, 3, '2026-05-01T00:00:00Z', '2026-05-20T23:59:59Z', 5, false, 'expired', 'archived', '00000000-0000-4000-8000-000000000003');

-- -----------------------------------------------------
-- SEEDING EXAM ATTEMPTS
-- -----------------------------------------------------
INSERT INTO exam_attempts (id, exam_id, user_id, started_at, submitted_at, score, correct_count, wrong_count, passed, status, answers) VALUES ('ea1', 'e1', '00000000-0000-4000-8000-000000000004', '2026-06-25T14:00:00Z', '2026-06-25T14:12:00Z', 7.5, 3, 1, true, 'submitted', '{"q1_1":[1],"q1_2":[1],"q1_3":[0,1],"q2_1":[1]}'::jsonb);
INSERT INTO exam_attempts (id, exam_id, user_id, started_at, submitted_at, score, correct_count, wrong_count, passed, status, answers) VALUES ('ea2', 'e2', '00000000-0000-4000-8000-000000000004', '2026-06-26T10:00:00Z', '2026-06-26T10:08:00Z', 10, 4, 0, true, 'submitted', '{"q3_1":[0],"q3_2":[0],"q10_1":[0],"q10_2":[0]}'::jsonb);
INSERT INTO exam_attempts (id, exam_id, user_id, started_at, submitted_at, score, correct_count, wrong_count, passed, status, answers) VALUES ('ea_3', 'e1', '00000000-0000-4000-8000-000000000004', '2026-06-24T09:32:54.294Z', '2026-06-24T09:44:54.294Z', 5, 2, 2, true, 'submitted', '{"q1_1":[1],"q1_2":[1]}'::jsonb);
INSERT INTO exam_attempts (id, exam_id, user_id, started_at, submitted_at, score, correct_count, wrong_count, passed, status, answers) VALUES ('ea_4', 'e1', '00000000-0000-4000-8000-000000000004', '2026-06-23T09:32:54.294Z', '2026-06-23T09:44:54.294Z', 5, 2, 2, true, 'submitted', '{"q1_1":[1],"q1_2":[1]}'::jsonb);
INSERT INTO exam_attempts (id, exam_id, user_id, started_at, submitted_at, score, correct_count, wrong_count, passed, status, answers) VALUES ('ea_5', 'e1', '00000000-0000-4000-8000-000000000004', '2026-06-22T09:32:54.294Z', '2026-06-22T09:44:54.294Z', 5, 2, 2, true, 'submitted', '{"q1_1":[1],"q1_2":[1]}'::jsonb);

-- -----------------------------------------------------
-- SEEDING EXAM ANSWERS
-- -----------------------------------------------------

-- -----------------------------------------------------
-- SEEDING NEWS
-- -----------------------------------------------------
INSERT INTO news (id, title, category, summary, content, image_url, visibility, status, author_id, published_at) VALUES ('n1', 'Ban CHQS xã Yên Thế tổ chức ra quân huấn luyện dân quân năm 2026', 'Tin tức huấn luyện', 'Sáng ngày 15/6, Ban Chỉ huy Quân sự xã Yên Thế tổ chức lễ ra quân huấn luyện và phát động phong trào thi đua cho lực lượng dân quân cơ động và dân quân tại chỗ.', 'Sáng ngày 15/6, trong không khí thi đua sôi nổi của địa phương, Ban CHQS xã Yên Thế đã tổ chức thành công Lễ ra quân huấn luyện dân quân năm 2026. Tham dự buổi lễ có đồng chí Bí thư Đảng ủy xã, Chủ tịch UBND xã cùng đại diện cơ quan quân sự cấp trên.

Năm nay, công tác huấn luyện chú trọng đổi mới nội dung, phương pháp, kết hợp chặt chẽ giữa huấn luyện quân sự với giáo dục chính trị pháp luật. Mục tiêu đặt ra là 100% chiến sĩ đạt yêu cầu kiểm tra nhận thức, trong đó có trên 75% đạt loại Khá, Giỏi.', 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=600', 'public', 'published', '00000000-0000-4000-8000-000000000002', '2026-06-15T09:00:00Z');
INSERT INTO news (id, title, category, summary, content, image_url, visibility, status, author_id, published_at) VALUES ('n2', 'Tuyên dương gương dân quân dũng cảm cứu hộ tài sản nhân dân trong bão lũ', 'Gương sáng chiến sĩ', 'Chiến sĩ dân quân tại chỗ thôn Tân Sỏi - đồng chí Hoàng Văn Nam vừa được Đảng ủy, UBND xã tuyên dương khen thưởng đột xuất vì hành động dũng cảm cứu tài sản nhân dân.', 'Trong đợt mưa lũ lịch sử ảnh hưởng bởi hoàn lưu bão vừa qua, nước sông dâng cao đột ngột gây ngập úng nghiêm trọng nhiều hộ dân tại thôn Tân Sỏi. Nhận được tin báo cứu hộ khẩn cấp, đồng chí Hoàng Văn Nam thuộc tổ dân quân tại chỗ thôn Tân Sỏi đã không quản ngại nguy hiểm, bơi qua dòng nước xiết để hỗ trợ vận chuyển an toàn tài sản và 3 người già, trẻ nhỏ đến nơi tránh trú an toàn.

Hành động dũng cảm, hết lòng vì nhân dân của đồng chí Nam đã tô thắm thêm hình ảnh cao đẹp của bộ đội Cụ Hồ và chiến sĩ Sao Vuông trong lòng nhân dân địa phương. Buổi lễ tuyên dương khen thưởng đã được tổ chức trang trọng tại Nhà văn hóa xã Yên Thế vào sáng qua.', 'https://images.unsplash.com/photo-1508962914676-134849a727f0?w=600', 'public', 'published', '00000000-0000-4000-8000-000000000002', '2026-06-24T08:00:00Z');
INSERT INTO news (id, title, category, summary, content, image_url, visibility, status, author_id, published_at) VALUES ('n3', 'Thông báo lịch sinh hoạt chính trị và học tập Nghị quyết tháng 6 năm 2026', 'Thông báo đơn vị', 'Ban CHQS xã Yên Thế thông báo lịch học tập chính trị tập trung về xây dựng lập trường tư tưởng cách mạng vững vàng cho toàn thể cán bộ chiến sĩ.', 'Để thực hiện nghiêm túc kế hoạch giáo dục chính trị năm 2026, Đảng ủy quân sự xã thông báo lịch học tập chuyên đề tập trung:
* **Thời gian:** 08h00 ngày Chủ nhật, ngày 28/06/2026.
* **Địa điểm:** Hội trường UBND xã Yên Thế.
* **Thành phần:** Toàn bộ cán bộ, chiến sĩ dân quân cơ động, dân quân tại chỗ các thôn.
* **Nội dung:** Quán triệt chuyên đề "Kiên định mục tiêu lý tưởng cách mạng" và hướng dẫn thảo luận tự soi, tự sửa.', 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=600', 'internal', 'published', '00000000-0000-4000-8000-000000000002', '2026-06-20T14:00:00Z');
INSERT INTO news (id, title, category, summary, content, image_url, visibility, status, author_id, published_at) VALUES ('n4', 'Tin tức giáo dục quân sự địa phương số 4: Đạt kết quả cao trong huấn luyện', 'Bản tin tuyên truyền', 'Tóm tắt bản tin thời sự quốc phòng an ninh địa bàn Yên Thế số 4, đánh giá công tác giáo dục chính trị pháp luật đạt chất lượng cao.', 'Chi tiết bản tin thời sự: Lực lượng vũ trang xã Yên Thế luôn nỗ lực đạt kết quả tốt nhất trong các bài học chính trị lý luận và kỹ thuật chiến thuật quân sự năm 2026.

Sự chỉ đạo sát sao của Ban chỉ huy là động lực to lớn giúp các chiến sĩ phấn đấu rèn luyện, nâng cao cảnh giác sẵn sàng chiến đấu giữ vững bình yên cho quê hương bản làng cách mạng Yên Thế anh hùng.', 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=600', 'public', 'published', '00000000-0000-4000-8000-000000000002', '2026-06-23T09:32:54.294Z');
INSERT INTO news (id, title, category, summary, content, image_url, visibility, status, author_id, published_at) VALUES ('n5', 'Tin tức giáo dục quân sự địa phương số 5: Đạt kết quả cao trong huấn luyện', 'Thông báo nội bộ', 'Tóm tắt bản tin thời sự quốc phòng an ninh địa bàn Yên Thế số 5, đánh giá công tác giáo dục chính trị pháp luật đạt chất lượng cao.', 'Chi tiết bản tin thời sự: Lực lượng vũ trang xã Yên Thế luôn nỗ lực đạt kết quả tốt nhất trong các bài học chính trị lý luận và kỹ thuật chiến thuật quân sự năm 2026.

Sự chỉ đạo sát sao của Ban chỉ huy là động lực to lớn giúp các chiến sĩ phấn đấu rèn luyện, nâng cao cảnh giác sẵn sàng chiến đấu giữ vững bình yên cho quê hương bản làng cách mạng Yên Thế anh hùng.', 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=600', 'public', 'published', '00000000-0000-4000-8000-000000000002', '2026-06-22T09:32:54.294Z');
INSERT INTO news (id, title, category, summary, content, image_url, visibility, status, author_id, published_at) VALUES ('n6', 'Tin tức giáo dục quân sự địa phương số 6: Đạt kết quả cao trong huấn luyện', 'Bản tin tuyên truyền', 'Tóm tắt bản tin thời sự quốc phòng an ninh địa bàn Yên Thế số 6, đánh giá công tác giáo dục chính trị pháp luật đạt chất lượng cao.', 'Chi tiết bản tin thời sự: Lực lượng vũ trang xã Yên Thế luôn nỗ lực đạt kết quả tốt nhất trong các bài học chính trị lý luận và kỹ thuật chiến thuật quân sự năm 2026.

Sự chỉ đạo sát sao của Ban chỉ huy là động lực to lớn giúp các chiến sĩ phấn đấu rèn luyện, nâng cao cảnh giác sẵn sàng chiến đấu giữ vững bình yên cho quê hương bản làng cách mạng Yên Thế anh hùng.', 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=600', 'public', 'published', '00000000-0000-4000-8000-000000000002', '2026-06-21T09:32:54.294Z');
INSERT INTO news (id, title, category, summary, content, image_url, visibility, status, author_id, published_at) VALUES ('n7', 'Tin tức giáo dục quân sự địa phương số 7: Đạt kết quả cao trong huấn luyện', 'Thông báo nội bộ', 'Tóm tắt bản tin thời sự quốc phòng an ninh địa bàn Yên Thế số 7, đánh giá công tác giáo dục chính trị pháp luật đạt chất lượng cao.', 'Chi tiết bản tin thời sự: Lực lượng vũ trang xã Yên Thế luôn nỗ lực đạt kết quả tốt nhất trong các bài học chính trị lý luận và kỹ thuật chiến thuật quân sự năm 2026.

Sự chỉ đạo sát sao của Ban chỉ huy là động lực to lớn giúp các chiến sĩ phấn đấu rèn luyện, nâng cao cảnh giác sẵn sàng chiến đấu giữ vững bình yên cho quê hương bản làng cách mạng Yên Thế anh hùng.', 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=600', 'public', 'published', '00000000-0000-4000-8000-000000000002', '2026-06-20T09:32:54.294Z');
INSERT INTO news (id, title, category, summary, content, image_url, visibility, status, author_id, published_at) VALUES ('n8', 'Tin tức giáo dục quân sự địa phương số 8: Đạt kết quả cao trong huấn luyện', 'Bản tin tuyên truyền', 'Tóm tắt bản tin thời sự quốc phòng an ninh địa bàn Yên Thế số 8, đánh giá công tác giáo dục chính trị pháp luật đạt chất lượng cao.', 'Chi tiết bản tin thời sự: Lực lượng vũ trang xã Yên Thế luôn nỗ lực đạt kết quả tốt nhất trong các bài học chính trị lý luận và kỹ thuật chiến thuật quân sự năm 2026.

Sự chỉ đạo sát sao của Ban chỉ huy là động lực to lớn giúp các chiến sĩ phấn đấu rèn luyện, nâng cao cảnh giác sẵn sàng chiến đấu giữ vững bình yên cho quê hương bản làng cách mạng Yên Thế anh hùng.', 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=600', 'public', 'published', '00000000-0000-4000-8000-000000000002', '2026-06-19T09:32:54.294Z');
INSERT INTO news (id, title, category, summary, content, image_url, visibility, status, author_id, published_at) VALUES ('n9', 'Tin tức giáo dục quân sự địa phương số 9: Đạt kết quả cao trong huấn luyện', 'Thông báo nội bộ', 'Tóm tắt bản tin thời sự quốc phòng an ninh địa bàn Yên Thế số 9, đánh giá công tác giáo dục chính trị pháp luật đạt chất lượng cao.', 'Chi tiết bản tin thời sự: Lực lượng vũ trang xã Yên Thế luôn nỗ lực đạt kết quả tốt nhất trong các bài học chính trị lý luận và kỹ thuật chiến thuật quân sự năm 2026.

Sự chỉ đạo sát sao của Ban chỉ huy là động lực to lớn giúp các chiến sĩ phấn đấu rèn luyện, nâng cao cảnh giác sẵn sàng chiến đấu giữ vững bình yên cho quê hương bản làng cách mạng Yên Thế anh hùng.', 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=600', 'public', 'published', '00000000-0000-4000-8000-000000000002', '2026-06-18T09:32:54.294Z');
INSERT INTO news (id, title, category, summary, content, image_url, visibility, status, author_id, published_at) VALUES ('n10', 'Tin tức giáo dục quân sự địa phương số 10: Đạt kết quả cao trong huấn luyện', 'Bản tin tuyên truyền', 'Tóm tắt bản tin thời sự quốc phòng an ninh địa bàn Yên Thế số 10, đánh giá công tác giáo dục chính trị pháp luật đạt chất lượng cao.', 'Chi tiết bản tin thời sự: Lực lượng vũ trang xã Yên Thế luôn nỗ lực đạt kết quả tốt nhất trong các bài học chính trị lý luận và kỹ thuật chiến thuật quân sự năm 2026.

Sự chỉ đạo sát sao của Ban chỉ huy là động lực to lớn giúp các chiến sĩ phấn đấu rèn luyện, nâng cao cảnh giác sẵn sàng chiến đấu giữ vững bình yên cho quê hương bản làng cách mạng Yên Thế anh hùng.', 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=600', 'public', 'published', '00000000-0000-4000-8000-000000000002', '2026-06-17T09:32:54.294Z');

-- -----------------------------------------------------
-- SEEDING NOTIFICATIONS
-- -----------------------------------------------------
INSERT INTO notifications (id, user_id, title, message, type, read, created_at) VALUES ('n_not1', '00000000-0000-4000-8000-000000000004', 'Bài kiểm tra mới được giao', 'Đồng chí có bài kiểm tra ''Kiểm tra trắc nghiệm Giáo dục chính trị & Pháp luật đợt 1 năm 2026'' cần hoàn thành trước ngày 05/07.', 'exam', false, '2026-06-20T00:00:00Z');
INSERT INTO notifications (id, user_id, title, message, type, read, created_at) VALUES ('n_not2', '00000000-0000-4000-8000-000000000004', 'Tài liệu học tập bắt buộc', 'Đại đội trưởng vừa giao chuyên đề học tập bắt buộc: ''Phòng chống thông tin xấu độc trên không gian mạng''.', 'info', true, '2026-06-22T14:00:00Z');
INSERT INTO notifications (id, user_id, title, message, type, read, created_at) VALUES ('n_not_3', '00000000-0000-4000-8000-000000000004', 'Thông báo cập nhật bài học số 3', 'Hệ thống vừa tải giáo án mới hoặc cập nhật điểm học tập của đồng chí.', 'success', false, '2026-06-25T21:32:54.294Z');
INSERT INTO notifications (id, user_id, title, message, type, read, created_at) VALUES ('n_not_4', '00000000-0000-4000-8000-000000000004', 'Thông báo cập nhật bài học số 4', 'Hệ thống vừa tải giáo án mới hoặc cập nhật điểm học tập của đồng chí.', 'info', true, '2026-06-25T09:32:54.294Z');
INSERT INTO notifications (id, user_id, title, message, type, read, created_at) VALUES ('n_not_5', '00000000-0000-4000-8000-000000000004', 'Thông báo cập nhật bài học số 5', 'Hệ thống vừa tải giáo án mới hoặc cập nhật điểm học tập của đồng chí.', 'info', false, '2026-06-24T21:32:54.294Z');
INSERT INTO notifications (id, user_id, title, message, type, read, created_at) VALUES ('n_not_6', '00000000-0000-4000-8000-000000000004', 'Thông báo cập nhật bài học số 6', 'Hệ thống vừa tải giáo án mới hoặc cập nhật điểm học tập của đồng chí.', 'success', true, '2026-06-24T09:32:54.294Z');
INSERT INTO notifications (id, user_id, title, message, type, read, created_at) VALUES ('n_not_7', '00000000-0000-4000-8000-000000000004', 'Thông báo cập nhật bài học số 7', 'Hệ thống vừa tải giáo án mới hoặc cập nhật điểm học tập của đồng chí.', 'info', false, '2026-06-23T21:32:54.294Z');
INSERT INTO notifications (id, user_id, title, message, type, read, created_at) VALUES ('n_not_8', '00000000-0000-4000-8000-000000000004', 'Thông báo cập nhật bài học số 8', 'Hệ thống vừa tải giáo án mới hoặc cập nhật điểm học tập của đồng chí.', 'info', true, '2026-06-23T09:32:54.294Z');
INSERT INTO notifications (id, user_id, title, message, type, read, created_at) VALUES ('n_not_9', '00000000-0000-4000-8000-000000000004', 'Thông báo cập nhật bài học số 9', 'Hệ thống vừa tải giáo án mới hoặc cập nhật điểm học tập của đồng chí.', 'success', false, '2026-06-22T21:32:54.294Z');
INSERT INTO notifications (id, user_id, title, message, type, read, created_at) VALUES ('n_not_10', '00000000-0000-4000-8000-000000000004', 'Thông báo cập nhật bài học số 10', 'Hệ thống vừa tải giáo án mới hoặc cập nhật điểm học tập của đồng chí.', 'info', true, '2026-06-22T09:32:54.294Z');

-- -----------------------------------------------------
-- SEEDING AUDIT LOGS
-- -----------------------------------------------------
INSERT INTO audit_logs (id, user_id, user_name, action, entity_type, entity_id, metadata, created_at) VALUES ('log_1', '00000000-0000-4000-8000-000000000001', 'Phạm Thị Lan', 'Khởi tạo hệ thống', 'system', 'system', '{"version":"1.0.0"}'::jsonb, '2026-06-20T08:00:00Z');
INSERT INTO audit_logs (id, user_id, user_name, action, entity_type, entity_id, metadata, created_at) VALUES ('log_2', '00000000-0000-4000-8000-000000000003', 'Nguyễn Văn Hà', 'Tải lên giáo án', 'topic', 't1', '{"title":"Giáo dục chính trị"}'::jsonb, '2026-06-21T09:00:00Z');
INSERT INTO audit_logs (id, user_id, user_name, action, entity_type, entity_id, metadata, created_at) VALUES ('log_3', '00000000-0000-4000-8000-000000000002', 'Trần Đức Cường', 'Đăng tải bản tin', 'news', 'entity_3', '{"message":"Hoạt động ghi nhận tự động"}'::jsonb, '2026-06-26T21:32:54.294Z');
INSERT INTO audit_logs (id, user_id, user_name, action, entity_type, entity_id, metadata, created_at) VALUES ('log_4', '00000000-0000-4000-8000-000000000003', 'Nguyễn Văn Hà', 'Phê duyệt tài khoản', 'user', 'entity_4', '{"message":"Hoạt động ghi nhận tự động"}'::jsonb, '2026-06-26T17:32:54.294Z');
INSERT INTO audit_logs (id, user_id, user_name, action, entity_type, entity_id, metadata, created_at) VALUES ('log_5', '00000000-0000-4000-8000-000000000002', 'Trần Đức Cường', 'Phê duyệt tài khoản', 'user', 'entity_5', '{"message":"Hoạt động ghi nhận tự động"}'::jsonb, '2026-06-26T13:32:54.294Z');
INSERT INTO audit_logs (id, user_id, user_name, action, entity_type, entity_id, metadata, created_at) VALUES ('log_6', '00000000-0000-4000-8000-000000000003', 'Nguyễn Văn Hà', 'Đăng tải bản tin', 'news', 'entity_6', '{"message":"Hoạt động ghi nhận tự động"}'::jsonb, '2026-06-26T09:32:54.294Z');
INSERT INTO audit_logs (id, user_id, user_name, action, entity_type, entity_id, metadata, created_at) VALUES ('log_7', '00000000-0000-4000-8000-000000000002', 'Trần Đức Cường', 'Phê duyệt tài khoản', 'user', 'entity_7', '{"message":"Hoạt động ghi nhận tự động"}'::jsonb, '2026-06-26T05:32:54.294Z');
INSERT INTO audit_logs (id, user_id, user_name, action, entity_type, entity_id, metadata, created_at) VALUES ('log_8', '00000000-0000-4000-8000-000000000003', 'Nguyễn Văn Hà', 'Phê duyệt tài khoản', 'user', 'entity_8', '{"message":"Hoạt động ghi nhận tự động"}'::jsonb, '2026-06-26T01:32:54.294Z');
INSERT INTO audit_logs (id, user_id, user_name, action, entity_type, entity_id, metadata, created_at) VALUES ('log_9', '00000000-0000-4000-8000-000000000002', 'Trần Đức Cường', 'Đăng tải bản tin', 'news', 'entity_9', '{"message":"Hoạt động ghi nhận tự động"}'::jsonb, '2026-06-25T21:32:54.294Z');
INSERT INTO audit_logs (id, user_id, user_name, action, entity_type, entity_id, metadata, created_at) VALUES ('log_10', '00000000-0000-4000-8000-000000000003', 'Nguyễn Văn Hà', 'Phê duyệt tài khoản', 'user', 'entity_10', '{"message":"Hoạt động ghi nhận tự động"}'::jsonb, '2026-06-25T17:32:54.294Z');
